import { ObjetValeur } from '../../../domain/ValueObject';

export const PERMISSIONS_SECURITE = [
  'referentiel.read',
  'referentiel.write',
  'annees.read',
  'annees.write',
  'eleves.read',
  'eleves.write',
  'abandons.write',
  'transferts.write',
  'paiements.read',
  'paiements.write',
  'caisse.read',
  'caisse.write',
  'cotes.read',
  'cotes.write',
  'bulletins.read',
  'bulletins.generate',
  'proclamations.read',
  'proclamations.generate',
  'notifications.send',
  'notifications.create',
  'notifications.read',
  'notifications.timeline.read',
  'notifications.acknowledge',
  'notifications.escalate',
  'notifications.retry.execute',
  'notifications.retry.read',
  'notifications.replay.execute',
  'notifications.replay.read',
  'notifications.monitoring.read',
  'notifications.dead-letter.read',
  'notifications.admin.archives.read',
  'notifications.admin.tenant.read',
  'notifications.admin.escalation.read',
  'notifications.realtime.read',
  'notifications.realtime.publish',
  'sms.send',
  'convocations.send',
  'utilisateurs.read',
  'utilisateurs.write',
  'roles.read',
  'roles.write',
  'permissions.read',
  'permissions.write',
  'security.center.read',
  'security.accounts.read',
  'security.accounts.write',
  'security.accounts.lifecycle',
  'security.admin.organizations.read',
  'security.admin.organizations.write',
  'security.admin.schools.read',
  'security.admin.schools.write',
  'security.admin.schools.emergency.write',
  'security.roles.read',
  'security.roles.write',
  'security.assignments.read',
  'security.assignments.write',
  'security.sessions.read',
  'security.sessions.revoke',
  'security.attempts.read',
  'security.accounts.unlock',
  'security.audit.read',
  'security.policies.read',
  'audit.read',
  'audit.timeline.read',
  'audit.history.read',
  'audit.monitoring.read',
  'audit.security.read',
  'audit.analytics.read',
  'audit.finance.read',
  'audit.technical.read',
  'audit.export',
  'audit.export.read',
  'audit.export.download',
  'audit.export.delete',
  'audit.analytics.export',
  'audit.replay',
  'audit.retry',
  'audit.sync',
  'audit.sync.read',
  'audit.sync.retry',
  'audit.sync.replay',
  'audit.sync.recovery',
  'audit.sync.status.write',
  'audit.retention.read',
  'audit.retention.archive',
  'audit.retention.purge',
  'audit.health.read',
  'audit.internal.rebuild',
  'audit.internal.recovery',
  'audit.admin.recovery',
  'audit.admin.replay',
  'audit.admin.retention',
  'monitoring.read',
  'monitoring.dashboard.read',
  'monitoring.observability.read',
  'monitoring.health.read',
  'monitoring.health.snapshot.read',
  'monitoring.incidents.read',
  'monitoring.incidents.create',
  'monitoring.incidents.escalate',
  'monitoring.alerts.read',
  'monitoring.alerts.create',
  'monitoring.alerts.resolve',
  'monitoring.diagnostics.read',
  'monitoring.diagnostics.create',
  'monitoring.capacity.read',
  'monitoring.capacity.calculate',
  'monitoring.saturation.calculate',
  'monitoring.traces.read',
  'monitoring.traces.create',
  'configuration.read',
  'configuration.create',
  'configuration.update',
  'configuration.delete',
  'configuration.lock',
  'configuration.unlock',
  'configuration.override',
  'configuration.effective.read',
  'configuration.snapshots.create',
  'configuration.snapshots.compare',
  'configuration.propagate',
  'configuration.reload',
  'configuration.validate',
  'configuration.modules.read',
  'configuration.modules.organization.write',
  'configuration.modules.school.write',
  'forensic.read',
  'forensic.timeline.read',
  'forensic.incidents',
  'forensic.security',
  'forensic.export',
  'forensic.replay',
] as const;

export type PermissionSecuriteValeur = (typeof PERMISSIONS_SECURITE)[number];

// Cet objet valeur represente une permission officielle du module SECURITY.
export class PermissionSecurite extends ObjetValeur<{ valeur: PermissionSecuriteValeur }> {
  constructor(valeur: string) {
    const valeurNormalisee = String(valeur || '').trim() as PermissionSecuriteValeur;
    if (!PERMISSIONS_SECURITE.includes(valeurNormalisee)) {
      throw new Error('La permission de securite est invalide.');
    }

    super({ valeur: valeurNormalisee });
  }

  public obtenirValeur(): PermissionSecuriteValeur {
    return this.proprietes.valeur;
  }
}
