// Ce value object enumere les differents types de frais du domaine.
export enum TypeFrais {
  FRAIS_SCOLAIRES = 'FRAIS_SCOLAIRES',
  FRAIS_ETAT = 'FRAIS_ETAT',
  FRAIS_TECHNIQUES = 'FRAIS_TECHNIQUES',
  FRAIS_ENROLEMENT_TENASOSP = 'FRAIS_ENROLEMENT_TENASOSP',
  FRAIS_PARTICIPATION_TENASOSP = 'FRAIS_PARTICIPATION_TENASOSP',
  FRAIS_ENROLEMENT_EXETAT = 'FRAIS_ENROLEMENT_EXETAT',
  FRAIS_PARTICIPATION_EXETAT = 'FRAIS_PARTICIPATION_EXETAT',
  FRAIS_BULLETIN = 'FRAIS_BULLETIN',
  FRAIS_MINERVAL = 'FRAIS_MINERVAL',
  FRAIS_INSCRIPTION = 'FRAIS_INSCRIPTION',
  AUTRE = 'AUTRE',
}
