import { reactive } from 'vue';
import { registerScopedLifecycleStore } from '../../../shared/lifecycle/frontend-lifecycle.runtime';
import { notificationsService } from '../../../services/notifications.service';
import { lireEnveloppe, lireListe } from '../mappers/monitoring.mapper';
import type { AlertResponse, CapacityPayload, CapacityResponse, CaptureTracePayload, CreateAlertPayload, DiagnosticResponse, GenerateDiagnosticPayload, HealthSnapshotResponse, IncidentResponse, MonitoringDashboardResponse, ObservabilityResponse, OpenIncidentPayload, SaturationPayload, SaturationResponse, SystemStateResponse, TraceResponse } from '../models/monitoring.model';
import { lireContexteApiMonitoring, monitoringApi } from '../services/monitoring.api';
type Status='idle'|'loading'|'ready'|'error';
interface MonitoringState{status:Status;errorMessage:string|null;stateData:SystemStateResponse|null;dashboardData:MonitoringDashboardResponse|null;observabilityData:ObservabilityResponse|null;healthData:SystemStateResponse|null;healthSnapshotData:HealthSnapshotResponse|null;incidents:readonly IncidentResponse[];alerts:readonly AlertResponse[];diagnostics:readonly DiagnosticResponse[];capacityData:readonly CapacityResponse[];saturationData:SaturationResponse|null;traces:readonly TraceResponse[];lastMutation:AlertResponse|IncidentResponse|DiagnosticResponse|CapacityResponse|SaturationResponse|TraceResponse|null;}
const state=reactive<MonitoringState>({status:'idle',errorMessage:null,stateData:null,dashboardData:null,observabilityData:null,healthData:null,healthSnapshotData:null,incidents:[],alerts:[],diagnostics:[],capacityData:[],saturationData:null,traces:[],lastMutation:null});
async function run(action:()=>Promise<void>,fallback:string){state.status='loading';state.errorMessage=null;try{await action();state.status='ready'}catch(e){state.status='error';state.errorMessage=e instanceof Error?e.message:fallback}}
export function useMonitoringStore(){
 const c=()=>lireContexteApiMonitoring();
 const chargerEtat=()=>run(async()=>{state.stateData=lireEnveloppe(await monitoringApi.lireEtat(c()),null)},'Lecture etat impossible.');
 const chargerDashboard=()=>run(async()=>{state.dashboardData=lireEnveloppe(await monitoringApi.lireDashboard(c()),null)},'Lecture dashboard impossible.');
 const chargerObservabilite=()=>run(async()=>{state.observabilityData=lireEnveloppe(await monitoringApi.lireObservabilite(c()),null)},'Lecture observabilite impossible.');
 const chargerHealth=()=>run(async()=>{state.healthData=lireEnveloppe(await monitoringApi.lireHealth(c()),null);state.healthSnapshotData=lireEnveloppe(await monitoringApi.lireHealthSnapshot(c()),null)},'Lecture sante impossible.');
 const chargerIncidents=()=>run(async()=>{state.incidents=lireListe<IncidentResponse>(await monitoringApi.lireIncidents(c()))},'Lecture incidents impossible.');
 const ouvrirIncident=(p:OpenIncidentPayload)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.ouvrirIncident(p,c()),null);await refreshIncidents();notificationsService.succes('Incident ouvert','L’incident a ete cree et synchronise.')},'Ouverture incident impossible.');
 const escaladerIncident=(id:string)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.escaladerIncident(id,c()),null);await refreshIncidents();notificationsService.succes('Incident escalade','La transition a ete enregistree.')},'Escalade incident impossible.');
 const refreshIncidents=async()=>{state.incidents=lireListe<IncidentResponse>(await monitoringApi.lireIncidents(c()))};
 const chargerAlertes=()=>run(async()=>{state.alerts=lireListe<AlertResponse>(await monitoringApi.lireAlertes(c()))},'Lecture alertes impossible.');
 const creerAlerte=(p:CreateAlertPayload)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.creerAlerte(p,c()),null);state.alerts=lireListe<AlertResponse>(await monitoringApi.lireAlertes(c()));notificationsService.succes('Alerte creee','Le signal est maintenant visible dans le cockpit.')},'Creation alerte impossible.');
 const resoudreAlerte=(id:string)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.resoudreAlerte(id,c()),null);state.alerts=lireListe<AlertResponse>(await monitoringApi.lireAlertes(c()));notificationsService.succes('Alerte resolue','La resolution a ete prise en compte.')},'Resolution alerte impossible.');
 const chargerDiagnostics=()=>run(async()=>{state.diagnostics=lireListe<DiagnosticResponse>(await monitoringApi.lireDiagnostics(c()))},'Lecture diagnostics impossible.');
 const genererDiagnostic=(id:string,p:GenerateDiagnosticPayload)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.genererDiagnostic(id,p,c()),null);state.diagnostics=lireListe<DiagnosticResponse>(await monitoringApi.lireDiagnostics(c()));notificationsService.succes('Diagnostic genere','L’analyse est disponible dans l’historique.')},'Generation diagnostic impossible.');
 const chargerCapacite=()=>run(async()=>{state.capacityData=lireListe<CapacityResponse>(await monitoringApi.lireCapacite(c()))},'Lecture capacite impossible.');
 const calculerCapacite=(p:CapacityPayload)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.calculerCapacite(p,c()),null);state.capacityData=lireListe<CapacityResponse>(await monitoringApi.lireCapacite(c()));notificationsService.succes('Capacite calculee','Le snapshot de capacite a ete actualise.')},'Calcul capacite impossible.');
 const calculerSaturation=(p:SaturationPayload)=>run(async()=>{const r=lireEnveloppe<SaturationResponse|null>(await monitoringApi.calculerSaturation(p,c()),null);state.saturationData=r;state.lastMutation=r;notificationsService.succes('Saturation calculee','Le niveau de saturation a ete actualise.')},'Calcul saturation impossible.');
 const chargerTraces=()=>run(async()=>{state.traces=lireListe<TraceResponse>(await monitoringApi.lireTraces(c()))},'Lecture traces impossible.');
 const capturerTrace=(p:CaptureTracePayload)=>run(async()=>{state.lastMutation=lireEnveloppe(await monitoringApi.capturerTrace(p,c()),null);state.traces=lireListe<TraceResponse>(await monitoringApi.lireTraces(c()));notificationsService.succes('Trace capturee','La trace est disponible dans l’historique.')},'Capture trace impossible.');
 function reinitialiser(){Object.assign(state,{status:'idle',errorMessage:null,stateData:null,dashboardData:null,observabilityData:null,healthData:null,healthSnapshotData:null,incidents:[],alerts:[],diagnostics:[],capacityData:[],saturationData:null,traces:[],lastMutation:null})}
 registerScopedLifecycleStore('monitoring','platform',reinitialiser); return{state,chargerEtat,chargerDashboard,chargerObservabilite,chargerHealth,chargerIncidents,ouvrirIncident,escaladerIncident,chargerAlertes,creerAlerte,resoudreAlerte,chargerDiagnostics,genererDiagnostic,chargerCapacite,calculerCapacite,calculerSaturation,chargerTraces,capturerTrace,reinitialiser};
}
