/**
 * Ce value object enumere les valeurs de TypeEvenementParcours.
 */
export enum TypeEvenementParcours {
  INSCRIPTION = 'INSCRIPTION',
  VALIDATION_INSCRIPTION = 'VALIDATION_INSCRIPTION',
  AFFECTATION = 'AFFECTATION',
  CHANGEMENT_CLASSE = 'CHANGEMENT_CLASSE',
  ABANDON = 'ABANDON',
  TRANSFERT = 'TRANSFERT',
  REINTEGRATION = 'REINTEGRATION',
  REACTIVATION = 'REACTIVATION',
  ANNULATION_INSCRIPTION = 'ANNULATION_INSCRIPTION',
  SUSPENSION = 'SUSPENSION',
  DECES = 'DECES'
}
