import type { NiveauConfiguration } from '../enums';
import { MODULES_CONFIGURATION } from './ConfigurationModules';

export type TypeValeurConfigurationOfficielle =
  | 'booleen'
  | 'entier'
  | 'duree-secondes'
  | 'duree-millisecondes'
  | 'texte'
  | 'enum'
  | 'liste';

export type MomentInitialisationConfigurationOfficielle =
  | 'BOOTSTRAP_SYSTEME'
  | 'CREATION_ORGANISATION'
  | 'CREATION_ECOLE'
  | 'PREMIERE_UTILISATION'
  | 'AUCUN_DEFAUT_OFFICIEL';

export interface DefinitionConfigurationOfficielle {
  readonly key: string;
  readonly libelleMetier: string;
  readonly description: string;
  readonly scope: NiveauConfiguration;
  readonly categorie: string;
  readonly typeValeur: TypeValeurConfigurationOfficielle;
  readonly valeurParDefaut: unknown;
  readonly valeursAutorisees?: readonly unknown[];
  readonly minimum?: number;
  readonly maximum?: number;
  readonly unite?: string;
  readonly sensible: boolean;
  readonly obligatoire: boolean;
  readonly restartRequis: boolean;
  readonly moteurConsommateur: string;
  readonly momentInitialisation: MomentInitialisationConfigurationOfficielle;
  readonly preuve: string;
}

export const CATALOGUE_CONFIGURATION_OFFICIELLE: readonly DefinitionConfigurationOfficielle[] = [
  {
    key: 'runtime.retry.maxAttempts',
    libelleMetier: 'Tentatives maximales de reprise plateforme',
    description: 'Nombre maximal de reprises automatiques pour les traitements idempotents pilotes par la plateforme.',
    scope: 'SYSTEM',
    categorie: 'Parametres de la plateforme',
    typeValeur: 'entier',
    valeurParDefaut: 3,
    minimum: 1,
    maximum: 10,
    unite: 'tentatives',
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Moteur global de retry plateforme',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'RuntimeConfiguration.spec.ts et ConfigurationFactory.ts manipulent deja une valeur par defaut a 3.',
  },
  {
    key: 'runtime.replay.enabled',
    libelleMetier: 'Relecture automatique plateforme',
    description: 'Autorise ou bloque les reprises automatiques lorsque le moteur de replay estime qu une operation peut etre rejouee.',
    scope: 'SYSTEM',
    categorie: 'Parametres de la plateforme',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Moteur global de replay plateforme',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'RuntimeConfiguration.spec.ts et ConfigurationFactory.ts manipulent deja un replay actif par defaut.',
  },
  {
    key: 'runtime.cache.ttlSeconds',
    libelleMetier: 'Duree du cache plateforme',
    description: 'Duree de conservation du cache partage avant expiration automatique.',
    scope: 'SYSTEM',
    categorie: 'Parametres de la plateforme',
    typeValeur: 'duree-secondes',
    valeurParDefaut: 120,
    minimum: 30,
    maximum: 86400,
    unite: 'secondes',
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Cache partage plateforme',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationFactory.ts et RuntimeConfiguration.spec.ts manipulent deja un TTL de cache a 120 secondes.',
  },
  {
    key: 'notifications.providers.in_app.enabled',
    libelleMetier: 'Canal notifications dans l application',
    description: 'Active ou coupe le canal de notification interne a l application.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification active IN_APP par defaut.',
  },
  {
    key: 'notifications.providers.sms.enabled',
    libelleMetier: 'Canal SMS',
    description: 'Active ou coupe les envois SMS lorsque le fournisseur est disponible.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification active SMS par defaut.',
  },
  {
    key: 'notifications.providers.email.enabled',
    libelleMetier: 'Canal e mail',
    description: 'Active ou coupe les envois e mail lorsque le fournisseur est disponible.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification active EMAIL par defaut.',
  },
  {
    key: 'notifications.providers.whatsapp.enabled',
    libelleMetier: 'Canal WhatsApp',
    description: 'Active ou coupe les envois WhatsApp quand le fournisseur a ete configure.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: false,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification laisse WHATSAPP inactif par defaut.',
  },
  {
    key: 'notifications.providers.push.enabled',
    libelleMetier: 'Canal push',
    description: 'Active ou coupe les notifications push quand le fournisseur a ete configure.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: false,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification laisse PUSH inactif par defaut.',
  },
  {
    key: 'notifications.providers.webhook.enabled',
    libelleMetier: 'Canal webhook',
    description: 'Active ou coupe les diffusions webhook quand un endpoint a ete configure.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: false,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime providers',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationProvidersNotification laisse WEBHOOK inactif par defaut.',
  },
  {
    key: 'notifications.retry.enabled',
    libelleMetier: 'Retry notifications',
    description: 'Active ou coupe les reprises automatiques des notifications echouees.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime retry',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationNotificationRuntime hydrate notifications.retry.enabled a true.',
  },
  {
    key: 'notifications.retry.maxAttempts',
    libelleMetier: 'Tentatives de reprise notifications',
    description: 'Nombre maximal de reprises techniques pour une notification avant echec final.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'entier',
    valeurParDefaut: 5,
    minimum: 1,
    maximum: 20,
    unite: 'tentatives',
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime retry',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationNotificationRuntime hydrate notifications.retry.maxAttempts a 5.',
  },
  {
    key: 'notifications.retry.defaultBackoffMs',
    libelleMetier: 'Backoff notifications',
    description: 'Temps d attente applique entre deux tentatives de reprise de notification.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'duree-millisecondes',
    valeurParDefaut: 60000,
    minimum: 1000,
    maximum: 86400000,
    unite: 'millisecondes',
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime retry',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationNotificationRuntime hydrate notifications.retry.defaultBackoffMs a 60000.',
  },
  {
    key: 'notifications.replay.enabled',
    libelleMetier: 'Replay notifications',
    description: 'Autorise ou bloque le rejeu des notifications marquees comme rejouables.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'booleen',
    valeurParDefaut: true,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime replay',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationNotificationRuntime hydrate notifications.replay.enabled a true.',
  },
  {
    key: 'notifications.replay.batchSize',
    libelleMetier: 'Taille de lot replay notifications',
    description: 'Nombre maximal de notifications traitees en un lot de replay.',
    scope: 'SYSTEM',
    categorie: 'Notifications globales',
    typeValeur: 'entier',
    valeurParDefaut: 100,
    minimum: 1,
    maximum: 1000,
    unite: 'notifications',
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'ConfigurationNotificationRuntime replay',
    momentInitialisation: 'BOOTSTRAP_SYSTEME',
    preuve: 'ConfigurationNotificationRuntime hydrate notifications.replay.batchSize a 100.',
  },
  {
    key: 'modules.allowed',
    libelleMetier: 'Modules autorises pour une organisation',
    description: 'Catalogue des modules que l organisation peut mettre a disposition de ses ecoles.',
    scope: 'ORGANIZATION',
    categorie: 'Modules commerciaux',
    typeValeur: 'liste',
    valeurParDefaut: [...MODULES_CONFIGURATION],
    valeursAutorisees: [...MODULES_CONFIGURATION],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Resolution modulaire organisation',
    momentInitialisation: 'CREATION_ORGANISATION',
    preuve: 'La creation d organisation initialise explicitement le catalogue autorise; une absence reste fermee par securite.',
  },
  {
    key: 'modules.enabled',
    libelleMetier: 'Modules actifs dans une ecole',
    description: 'Liste des modules explicitement actives localement dans l ecole.',
    scope: 'SCHOOL',
    categorie: 'Modules commerciaux',
    typeValeur: 'liste',
    valeurParDefaut: [],
    valeursAutorisees: [...MODULES_CONFIGURATION],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Resolution modulaire ecole',
    momentInitialisation: 'CREATION_ECOLE',
    preuve: 'La doctrine officielle interdit toute activation automatique au niveau ecole.',
  },
  {
    key: 'preferences.theme',
    libelleMetier: 'Theme personnel de l utilisateur',
    description: 'Choix d apparence personnel du shell utilisateur.',
    scope: 'USER',
    categorie: 'Preferences personnelles',
    typeValeur: 'enum',
    valeurParDefaut: 'system',
    valeursAutorisees: ['light', 'dark', 'system'],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'Shell frontend utilisateur',
    momentInitialisation: 'PREMIERE_UTILISATION',
    preuve: 'Le theme frontend connait deja light et dark; la mission officialise selon appareil comme defaut.',
  },
  {
    key: 'notifications.preferences.muted',
    libelleMetier: 'Notifications personnelles coupees',
    description: 'Permet a l utilisateur de suspendre ses notifications personnelles non critiques.',
    scope: 'USER',
    categorie: 'Preferences de notification',
    typeValeur: 'booleen',
    valeurParDefaut: false,
    valeursAutorisees: [true, false],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'PreferencesNotification mute',
    momentInitialisation: 'PREMIERE_UTILISATION',
    preuve: 'PreferencesNotification porte deja le champ mute avec false par defaut.',
  },
  {
    key: 'notifications.preferences.preferredChannel',
    libelleMetier: 'Canal prefere',
    description: 'Canal personnel privilegie lorsque plusieurs diffusions restent autorisees.',
    scope: 'USER',
    categorie: 'Preferences de notification',
    typeValeur: 'enum',
    valeurParDefaut: 'IN_APP',
    valeursAutorisees: ['IN_APP', 'SMS', 'EMAIL', 'WHATSAPP', 'PUSH', 'WEBHOOK'],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'PreferencesNotification canalPrefere',
    momentInitialisation: 'PREMIERE_UTILISATION',
    preuve: 'PreferencesNotification porte deja canalPrefere; IN_APP reste le canal le plus neutre par defaut.',
  },
  {
    key: 'notifications.preferences.enabledChannels',
    libelleMetier: 'Canaux personnels autorises',
    description: 'Canaux personnels que l utilisateur accepte encore parmi ceux permis globalement.',
    scope: 'USER',
    categorie: 'Preferences de notification',
    typeValeur: 'liste',
    valeurParDefaut: ['IN_APP', 'EMAIL'],
    valeursAutorisees: ['IN_APP', 'SMS', 'EMAIL', 'WHATSAPP', 'PUSH', 'WEBHOOK'],
    sensible: false,
    obligatoire: true,
    restartRequis: false,
    moteurConsommateur: 'PreferencesNotification canauxAutorises',
    momentInitialisation: 'PREMIERE_UTILISATION',
    preuve: 'PreferencesNotification resout deja les canaux autorises d un destinataire.',
  },
] as const;

export function listerConfigurationsOfficielles(): readonly DefinitionConfigurationOfficielle[] {
  return CATALOGUE_CONFIGURATION_OFFICIELLE;
}

export function trouverConfigurationOfficielle(
  key: string,
): DefinitionConfigurationOfficielle | undefined {
  return CATALOGUE_CONFIGURATION_OFFICIELLE.find((definition) => definition.key === key);
}

export function listerConfigurationsOfficiellesParMoment(
  moment: MomentInitialisationConfigurationOfficielle,
): readonly DefinitionConfigurationOfficielle[] {
  return CATALOGUE_CONFIGURATION_OFFICIELLE.filter(
    (definition) => definition.momentInitialisation === moment,
  );
}
