import type { RouteRecordRaw } from 'vue-router';

export const routesMonitoring: RouteRecordRaw[] = [
  {
    path: 'monitoring',
    name: 'monitoring-home',
    component: () => import('./views/MonitoringOverviewView.vue'),
    props: {
      screenCode: 'CENTRE PLATEFORME',
      title: 'Centre Monitoring',
      description: 'Surveillez la disponibilite, les incidents, les alertes et la capacite d EduSync depuis un cockpit unique.',
      sectionTitle: 'Centre Monitoring',
      sectionDescription: 'Vue de travail consolidee des signaux essentiels de la plateforme.',
      loadingMessage: 'Les indicateurs de supervision sont en cours d actualisation.',
      mode: 'dashboard',
      showBack: false,
    },
    meta: { title: 'Monitoring' },
  },
  {
    path: 'monitoring/etat-systeme',
    name: 'monitoring-state',
    component: () => import('./views/MonitoringOverviewView.vue'),
    props: {
      screenCode: 'SCR-MON-001',
      title: 'Etat systeme',
      description: 'Lecture synthetique de l etat general de la plateforme.',
      sectionTitle: 'Etat systeme',
      sectionDescription: 'Lecture monitoring globale de la plateforme.',
      loadingMessage: 'Les indicateurs de l etat general sont en cours d actualisation.',
      mode: 'state',
    },
    meta: { title: 'Etat systeme' },
  },
  {
    path: 'monitoring/dashboard',
    name: 'monitoring-dashboard',
    component: () => import('./views/MonitoringOverviewView.vue'),
    props: {
      screenCode: 'SCR-MON-002',
      title: 'Dashboard monitoring',
      description: 'Vue consolidee des signaux monitoring pour le pilotage plateforme.',
      sectionTitle: 'Dashboard monitoring',
      sectionDescription: 'Vue de travail consolidee des signaux monitoring.',
      loadingMessage: 'Les indicateurs du tableau de bord sont en cours d actualisation.',
      mode: 'dashboard',
    },
    meta: { title: 'Dashboard monitoring' },
  },
  {
    path: 'monitoring/observabilite',
    name: 'monitoring-observability',
    component: () => import('./views/MonitoringOverviewView.vue'),
    props: {
      screenCode: 'SCR-MON-003',
      title: 'Observabilite',
      description: 'Lecture des signaux d observabilite de la plateforme.',
      sectionTitle: 'Observabilite',
      sectionDescription: 'Relecture des signaux et regroupements d observabilite.',
      loadingMessage: 'Les signaux de supervision sont en cours d actualisation.',
      mode: 'observability',
    },
    meta: { title: 'Observabilite' },
  },
  {
    path: 'monitoring/sante',
    name: 'monitoring-health',
    component: () => import('./views/MonitoringOverviewView.vue'),
    props: {
      screenCode: 'SCR-MON-004',
      title: 'Sante systeme',
      description: 'Lecture de la sante systeme et de son snapshot technique.',
      sectionTitle: 'Sante systeme',
      sectionDescription: 'Lecture health et snapshot sur le perimetre plateforme.',
      loadingMessage: 'Les indicateurs de disponibilite sont en cours d actualisation.',
      mode: 'health',
    },
    meta: { title: 'Sante systeme' },
  },
  {
    path: 'monitoring/incidents',
    name: 'monitoring-incidents',
    component: () => import('./views/MonitoringIncidentsView.vue'),
    meta: { title: 'Incidents monitoring' },
  },
  {
    path: 'monitoring/alertes',
    name: 'monitoring-alerts',
    component: () => import('./views/MonitoringAlertsView.vue'),
    meta: { title: 'Alertes monitoring' },
  },
  {
    path: 'monitoring/diagnostics',
    name: 'monitoring-diagnostics',
    component: () => import('./views/MonitoringDiagnosticsView.vue'),
    meta: { title: 'Diagnostics monitoring' },
  },
  {
    path: 'monitoring/capacite',
    name: 'monitoring-capacity',
    component: () => import('./views/MonitoringCapacityView.vue'),
    meta: { title: 'Capacite monitoring' },
  },
  {
    path: 'monitoring/traces',
    name: 'monitoring-traces',
    component: () => import('./views/MonitoringTracesView.vue'),
    meta: { title: 'Traces monitoring' },
  },
];
