import {
  type DefinitionColonnePostgresPaiements,
  type SchemaTablePostgresPaiements,
  creerSchemaTablePostgresPaiements,
} from './SchemaPostgres';

function identifiant(commentaire: string): DefinitionColonnePostgresPaiements {
  return {
    nom: 'id',
    type: 'uuid',
    obligatoire: true,
    commentaire,
  };
}

function version(commentaire: string): DefinitionColonnePostgresPaiements {
  return {
    nom: 'version',
    type: 'integer',
    obligatoire: true,
    valeurParDefautSql: '1',
    commentaire,
  };
}

function dateCreation(): DefinitionColonnePostgresPaiements {
  return {
    nom: 'cree_le',
    type: 'timestamptz',
    obligatoire: true,
    valeurParDefautSql: 'CURRENT_TIMESTAMP',
    commentaire: 'Date technique de creation.',
  };
}

// Ce fichier decrit les tables PostgreSQL du BC Paiements & Facturation.
export const schemasTablesPaiementsFacturation: readonly SchemaTablePostgresPaiements[] = [
  creerSchemaTablePostgresPaiements({
    nomTable: 'parametres_paiement_ecole',
    description: "Parametrage financier actif d'une ecole.",
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique du parametrage d'ecole."),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: "Ecole proprietaire du parametrage." },
      { nom: 'paiement_partiel_autorise', type: 'boolean', obligatoire: true, commentaire: 'Autorise ou non le paiement partiel.' },
      { nom: 'paiement_partiel_par_type_frais', type: 'jsonb', obligatoire: false, commentaire: 'Regles fines de paiement partiel par type de frais.' },
      { nom: 'politique_arrieres', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Politique metier des arrieres.' },
      { nom: 'autoriser_inscription_avec_dette', type: 'boolean', obligatoire: true, commentaire: "Autorise l'inscription avec dette." },
      { nom: 'bloquer_retrait_documents_si_dette', type: 'boolean', obligatoire: true, commentaire: 'Blocage de retrait des documents en cas de dette.' },
      { nom: 'appliquer_famille_nombreuse', type: 'boolean', obligatoire: true, commentaire: 'Active la logique famille nombreuse.' },
      { nom: 'nombre_enfants_seuil_famille_nombreuse', type: 'integer', obligatoire: false, commentaire: 'Seuil minimal du nombre denfants.' },
      { nom: 'modes_paiement_autorises', type: 'jsonb', obligatoire: true, commentaire: 'Liste des modes de paiement autorises.' },
      { nom: 'mois_obligatoire_inscription', type: 'varchar', taille: 40, obligatoire: false, commentaire: "Mois de frais a exiger a l'inscription." },
      { nom: 'exiger_frais_inscription', type: 'boolean', obligatoire: true, commentaire: "Indique si les frais d'inscription sont obligatoires." },
      { nom: 'actif', type: 'boolean', obligatoire: true, valeurParDefautSql: 'true', commentaire: 'Indique si ce parametrage est actif.' },
      version('Version metier du parametrage.'),
    ],
    references: [],
    index: [
      { nom: 'ux_parametres_paiement_ecole_id_ecole_actif', colonnes: ['id_ecole'], unique: true, conditionSql: 'actif = true', commentaire: 'Garantit un seul parametrage actif par ecole.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'grilles_tarification',
    description: 'Grilles tarifaires locales par ecole et par annee scolaire.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique de la grille tarifaire.'),
      { nom: 'id_organisation', type: 'uuid', obligatoire: false, commentaire: 'Organisation technique si elle est connue.' },
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire de la grille.' },
      { nom: 'id_annee_scolaire', type: 'uuid', obligatoire: true, commentaire: 'Annee scolaire concernee.' },
      { nom: 'type_frais', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Type de frais tarifaire.' },
      { nom: 'libelle', type: 'varchar', taille: 255, obligatoire: true, commentaire: 'Libelle metier de la grille.' },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: 'Montant entier applique.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise de la grille.' },
      { nom: 'section', type: 'varchar', taille: 80, obligatoire: false, commentaire: 'Section ciblee si applicable.' },
      { nom: 'categorie_frais_etat', type: 'varchar', taille: 80, obligatoire: false, commentaire: 'Categorie des frais Etat si applicable.' },
      { nom: 'categorie_technique', type: 'varchar', taille: 40, obligatoire: false, commentaire: 'Categorie technique si applicable.' },
      { nom: 'est_classe_tenasosp', type: 'boolean', obligatoire: false, commentaire: 'Indique si la grille cible une classe TENASOSP.' },
      { nom: 'est_classe_exetat', type: 'boolean', obligatoire: false, commentaire: 'Indique si la grille cible une classe EXETAT.' },
      { nom: 'est_classe_finaliste', type: 'boolean', obligatoire: false, commentaire: 'Indique si la grille cible une classe finaliste.' },
      { nom: 'mois_scolaire', type: 'varchar', taille: 40, obligatoire: false, commentaire: 'Mois scolaire cible si applicable.' },
      { nom: 'tranche_frais_etat', type: 'varchar', taille: 40, obligatoire: false, commentaire: 'Tranche Etat ciblee si applicable.' },
      { nom: 'obligatoire', type: 'boolean', obligatoire: true, commentaire: 'Indique si le frais est obligatoire.' },
      { nom: 'actif', type: 'boolean', obligatoire: true, valeurParDefautSql: 'true', commentaire: 'Indique si la grille est active.' },
      { nom: 'date_debut_validite', type: 'date', obligatoire: false, commentaire: 'Date de debut de validite.' },
      { nom: 'date_fin_validite', type: 'date', obligatoire: false, commentaire: 'Date de fin de validite.' },
      { nom: 'cree_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Acteur createur.' },
      dateCreation(),
      { nom: 'modifie_par', type: 'varchar', taille: 120, obligatoire: false, commentaire: 'Dernier acteur modificateur.' },
      { nom: 'modifie_le', type: 'timestamptz', obligatoire: false, commentaire: 'Date de derniere modification.' },
      version('Version metier de la grille tarifaire.'),
    ],
    references: [],
    index: [
      { nom: 'ix_grilles_tarification_ecole_annee_type', colonnes: ['id_ecole', 'id_annee_scolaire', 'type_frais'], unique: false, commentaire: 'Accelere la lecture des grilles par ecole, annee et type.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'obligations_financieres',
    description: 'Obligations financieres detaillees de chaque eleve.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique de l'obligation financiere."),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: "Ecole proprietaire de l'obligation." },
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve debiteur.' },
      { nom: 'id_annee_scolaire', type: 'uuid', obligatoire: true, commentaire: 'Annee scolaire rattachee.' },
      { nom: 'id_inscription_scolaire', type: 'uuid', obligatoire: false, commentaire: "Inscription scolaire d'origine si elle existe." },
      { nom: 'type_frais', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Type de frais de lobligation.' },
      { nom: 'reference_frais', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Reference metier du frais.' },
      { nom: 'libelle', type: 'varchar', taille: 255, obligatoire: true, commentaire: 'Libelle de presentation.' },
      { nom: 'montant_initial', type: 'integer', obligatoire: true, commentaire: 'Montant historique immuable.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise des montants.' },
      { nom: 'montant_paye', type: 'integer', obligatoire: true, commentaire: 'Montant deja paye.' },
      { nom: 'montant_exonere', type: 'integer', obligatoire: true, commentaire: 'Montant exonere.' },
      { nom: 'solde', type: 'integer', obligatoire: true, commentaire: 'Solde restant a payer.' },
      { nom: 'statut', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Statut courant de la dette.' },
      { nom: 'origine_creation', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Origine metier de creation.' },
      { nom: 'origine_paiement', type: 'varchar', taille: 80, obligatoire: false, commentaire: 'Origine du paiement applique si elle existe.' },
      { nom: 'id_grille_tarification', type: 'uuid', obligatoire: false, commentaire: "Grille tarifaire d'origine si applicable." },
      dateCreation(),
      { nom: 'cree_par', type: 'varchar', taille: 120, obligatoire: false, commentaire: 'Acteur createur si connu.' },
      version("Version metier de l'obligation."),
    ],
    references: [],
    index: [
      { nom: 'ux_obligations_financieres_eleve_annee_type_reference', colonnes: ['id_eleve', 'id_annee_scolaire', 'type_frais', 'reference_frais'], unique: true, commentaire: 'Garantit une obligation unique par eleve, annee, type et reference.' },
      { nom: 'ix_obligations_financieres_eleve_statut', colonnes: ['id_eleve', 'statut'], unique: false, commentaire: 'Accelere la lecture des obligations par eleve et statut.' },
      { nom: 'ix_obligations_financieres_ecole_annee', colonnes: ['id_ecole', 'id_annee_scolaire'], unique: false, commentaire: 'Accelere les lectures par ecole et annee.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'paiements',
    description: 'Paiements enregistres pour les obligations financieres.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique du paiement.'),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire du paiement.' },
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve ayant effectue ou subi le paiement.' },
      { nom: 'montant_total', type: 'integer', obligatoire: true, commentaire: 'Montant total du paiement.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du paiement.' },
      { nom: 'mode_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Mode de paiement utilise.' },
      { nom: 'type_frais_declare', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Type de frais declare par la commande.' },
      { nom: 'cible_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Cible metier du paiement.' },
      { nom: 'statut_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Statut courant du paiement.' },
      { nom: 'cree_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Caissier ou acteur createur.' },
      dateCreation(),
      { nom: 'idempotency_key', type: 'varchar', taille: 255, obligatoire: true, commentaire: "Cle d'idempotence de la commande." },
      version('Version metier du paiement.'),
    ],
    references: [],
    index: [
      { nom: 'ux_paiements_idempotency_key', colonnes: ['idempotency_key'], unique: true, commentaire: "Garantit l'idempotence des paiements." },
      { nom: 'ix_paiements_eleve', colonnes: ['id_eleve'], unique: false, commentaire: 'Accelere la lecture de lhistorique dun eleve.' },
      { nom: 'ix_paiements_ecole_creation', colonnes: ['id_ecole', 'cree_le'], unique: false, commentaire: 'Accelere les rapports par ecole et date.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'repartitions_paiement',
    description: "Detail d'affectation d'un paiement vers une obligation.",
    strategieIsolationTenant: 'non_applicable',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique de la repartition.'),
      { nom: 'id_paiement', type: 'uuid', obligatoire: true, commentaire: 'Paiement parent.' },
      { nom: 'id_obligation', type: 'uuid', obligatoire: true, commentaire: 'Obligation ciblee.' },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: 'Montant affecte.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du montant affecte.' },
      { nom: 'ordre_affectation', type: 'integer', obligatoire: true, commentaire: "Ordre d'affectation." },
      { nom: 'origine_affectation', type: 'varchar', taille: 80, obligatoire: true, commentaire: "Origine metier de l'affectation." },
    ],
    references: [
      { colonneLocale: 'id_paiement', tableReferencee: 'paiements', colonneReferencee: 'id', actionSuppression: 'cascade', actionMiseAJour: 'cascade', commentaire: 'Reference vers le paiement parent.' },
      { colonneLocale: 'id_obligation', tableReferencee: 'obligations_financieres', colonneReferencee: 'id', actionSuppression: 'restrict', actionMiseAJour: 'cascade', commentaire: "Reference vers l'obligation ciblee." },
    ],
    index: [
      { nom: 'ix_repartitions_paiement_paiement', colonnes: ['id_paiement'], unique: false, commentaire: 'Accelere la lecture des repartitions par paiement.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'recus_paiement',
    description: 'Recus emis pour chaque obligation reglee.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique du recu.'),
      { nom: 'numero_recu', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Numero unique du recu.' },
      { nom: 'id_paiement', type: 'uuid', obligatoire: true, commentaire: 'Paiement parent.' },
      { nom: 'id_obligation', type: 'uuid', obligatoire: true, commentaire: 'Obligation couverte.' },
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve concerne.' },
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire du recu.' },
      { nom: 'type_frais', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Type de frais du recu.' },
      { nom: 'reference_frais', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Reference du frais.' },
      { nom: 'libelle', type: 'varchar', taille: 255, obligatoire: true, commentaire: 'Libelle affiche sur le recu.' },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: 'Montant couvert par ce recu.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du recu.' },
      { nom: 'montant_lettres', type: 'text', obligatoire: true, commentaire: 'Montant en lettres.' },
      { nom: 'mode_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Mode de paiement.' },
      { nom: 'id_caissier', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Caissier emetteur.' },
      { nom: 'date_emission', type: 'timestamptz', obligatoire: true, commentaire: "Date d'emission du recu." },
      { nom: 'statut_recu', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Statut courant du recu.' },
    ],
    references: [
      { colonneLocale: 'id_paiement', tableReferencee: 'paiements', colonneReferencee: 'id', actionSuppression: 'restrict', actionMiseAJour: 'cascade', commentaire: 'Reference vers le paiement parent.' },
      { colonneLocale: 'id_obligation', tableReferencee: 'obligations_financieres', colonneReferencee: 'id', actionSuppression: 'restrict', actionMiseAJour: 'cascade', commentaire: 'Reference vers lobligation couverte.' },
    ],
    index: [
      { nom: 'ux_recus_paiement_numero_recu', colonnes: ['numero_recu'], unique: true, commentaire: 'Garantit lunicite du numero de recu.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'caisse_jour',
    description: 'Caisse journaliere unique par ecole et par date.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique de la caisse du jour.'),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire de la caisse.' },
      { nom: 'date_caisse', type: 'date', obligatoire: true, commentaire: 'Date metier de la caisse.' },
      { nom: 'statut', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Statut courant de la caisse.' },
      { nom: 'total_encaisse', type: 'integer', obligatoire: true, commentaire: 'Total encaisse courant.' },
      { nom: 'total_cash', type: 'integer', obligatoire: true, commentaire: 'Total cash courant.' },
      { nom: 'total_mobile_money', type: 'integer', obligatoire: true, commentaire: 'Total mobile money courant.' },
      { nom: 'total_par_caissier', type: 'jsonb', obligatoire: false, commentaire: 'Resume des totaux par caissier.' },
      { nom: 'total_fonds_anticipes', type: 'integer', obligatoire: true, commentaire: 'Total des fonds anticipes.' },
      { nom: 'total_fonds_consommes', type: 'integer', obligatoire: true, commentaire: 'Total des fonds consommes.' },
      { nom: 'disponible_reel', type: 'integer', obligatoire: true, commentaire: 'Disponible reel courant.' },
      { nom: 'ouverte_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Acteur ayant ouvert la caisse.' },
      { nom: 'ouverte_le', type: 'timestamptz', obligatoire: true, commentaire: "Date d'ouverture." },
      { nom: 'cloturee_par', type: 'varchar', taille: 120, obligatoire: false, commentaire: 'Acteur ayant cloture la caisse.' },
      { nom: 'cloturee_le', type: 'timestamptz', obligatoire: false, commentaire: 'Date de cloture.' },
      version('Version metier de la caisse.'),
    ],
    references: [],
    index: [
      { nom: 'ux_caisse_jour_ecole_date', colonnes: ['id_ecole', 'date_caisse'], unique: true, commentaire: 'Garantit une seule caisse par ecole et par date.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'operations_caisse',
    description: 'Operations detaillees rattachees a la caisse du jour.',
    strategieIsolationTenant: 'non_applicable',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique de l'operation de caisse."),
      { nom: 'id_caisse_jour', type: 'uuid', obligatoire: true, commentaire: 'Caisse parente.' },
      { nom: 'id_paiement', type: 'uuid', obligatoire: false, commentaire: 'Paiement lie si applicable.' },
      { nom: 'id_restitution', type: 'uuid', obligatoire: false, commentaire: 'Restitution liee si applicable.' },
      { nom: 'id_annulation', type: 'uuid', obligatoire: false, commentaire: 'Annulation liee si applicable.' },
      { nom: 'type_operation', type: 'varchar', taille: 40, obligatoire: true, commentaire: "Type d'operation de caisse." },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: "Montant de l'operation." },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: "Devise de l'operation." },
      { nom: 'mode_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Mode de paiement concerne.' },
      { nom: 'id_caissier', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Caissier responsable.' },
      { nom: 'date_operation', type: 'timestamptz', obligatoire: true, commentaire: "Date de l'operation." },
    ],
    references: [
      { colonneLocale: 'id_caisse_jour', tableReferencee: 'caisse_jour', colonneReferencee: 'id', actionSuppression: 'cascade', actionMiseAJour: 'cascade', commentaire: 'Reference vers la caisse parente.' },
    ],
    index: [
      { nom: 'ix_operations_caisse_id_caisse_jour', colonnes: ['id_caisse_jour'], unique: false, commentaire: 'Accelere la lecture des operations par caisse.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'exonerations',
    description: 'Exonerations accordees sur les obligations financieres.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique de l'exoneration."),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: "Ecole proprietaire de l'exoneration." },
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve beneficiaire.' },
      { nom: 'id_obligation', type: 'uuid', obligatoire: true, commentaire: 'Obligation exoneree.' },
      { nom: 'type_exoneration', type: 'varchar', taille: 40, obligatoire: true, commentaire: "Type d'exoneration." },
      { nom: 'montant_exonere', type: 'integer', obligatoire: true, commentaire: 'Montant exonere.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du montant exonere.' },
      { nom: 'pourcentage', type: 'integer', obligatoire: false, commentaire: 'Pourcentage applique si applicable.' },
      { nom: 'raison', type: 'text', obligatoire: true, commentaire: "Raison metier de l'exoneration." },
      { nom: 'valide_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Acteur valideur.' },
      { nom: 'validee_le', type: 'timestamptz', obligatoire: true, commentaire: 'Date de validation.' },
      { nom: 'statut', type: 'varchar', taille: 40, obligatoire: true, commentaire: "Statut de l'exoneration." },
    ],
    references: [],
    index: [
      { nom: 'ix_exonerations_eleve', colonnes: ['id_eleve'], unique: false, commentaire: 'Accelere la lecture des exonerations par eleve.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'plans_anticipation_frais',
    description: 'Plans de lissage et danticipation de frais.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique du plan danticipation.'),
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire du plan.' },
      { nom: 'id_annee_scolaire', type: 'uuid', obligatoire: true, commentaire: 'Annee scolaire concernee.' },
      { nom: 'nom', type: 'varchar', taille: 255, obligatoire: true, commentaire: 'Nom metier du plan.' },
      { nom: 'type_plan', type: 'varchar', taille: 80, obligatoire: true, commentaire: 'Type de plan danticipation.' },
      { nom: 'mois_cibles', type: 'jsonb', obligatoire: true, commentaire: 'Mois finances par anticipation.' },
      { nom: 'mois_supports', type: 'jsonb', obligatoire: true, commentaire: 'Mois supports de lissage.' },
      { nom: 'obligatoire', type: 'boolean', obligatoire: true, commentaire: 'Indique si le plan est obligatoire.' },
      { nom: 'actif', type: 'boolean', obligatoire: true, commentaire: 'Indique si le plan est actif.' },
      { nom: 'date_debut', type: 'date', obligatoire: false, commentaire: 'Date de debut dapplication.' },
      { nom: 'date_fin', type: 'date', obligatoire: false, commentaire: 'Date de fin dapplication.' },
      version('Version metier du plan danticipation.'),
    ],
    references: [],
    index: [
      { nom: 'ix_plans_anticipation_ecole_annee', colonnes: ['id_ecole', 'id_annee_scolaire'], unique: false, commentaire: 'Accelere la lecture des plans par ecole et annee.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'restitutions',
    description: "Restitutions d'excedents lies aux paiements.",
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant('Identifiant technique de la restitution.'),
      { nom: 'id_paiement', type: 'uuid', obligatoire: true, commentaire: 'Paiement a lorigine de lexcedent.' },
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire de la restitution.' },
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve concerne.' },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: 'Montant restitue.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du montant.' },
      { nom: 'raison', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Raison metier de la restitution.' },
      { nom: 'effectue_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Acteur ayant effectue la restitution.' },
      { nom: 'effectue_le', type: 'timestamptz', obligatoire: true, commentaire: 'Date de restitution.' },
    ],
    references: [],
    index: [],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'annulations_paiement',
    description: 'Annulations financieres avec operations inverses.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique de l'annulation."),
      { nom: 'id_paiement', type: 'uuid', obligatoire: true, commentaire: 'Paiement annule.' },
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: "Ecole proprietaire de l'annulation." },
      { nom: 'raison', type: 'text', obligatoire: true, commentaire: "Raison metier de l'annulation." },
      { nom: 'annule_par', type: 'varchar', taille: 120, obligatoire: true, commentaire: 'Acteur ayant annule le paiement.' },
      { nom: 'annule_le', type: 'timestamptz', obligatoire: true, commentaire: "Date d'annulation." },
    ],
    references: [],
    index: [
      { nom: 'ux_annulations_paiement_id_paiement', colonnes: ['id_paiement'], unique: true, commentaire: 'Garantit une seule annulation par paiement.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'operations_inverses_paiement',
    description: "Operations inverses rattachees a une annulation de paiement.",
    strategieIsolationTenant: 'non_applicable',
    clePrimaire: ['id_operation_inverse'],
    colonnes: [
      { nom: 'id_annulation', type: 'uuid', obligatoire: true, commentaire: 'Annulation parente.' },
      { nom: 'id_operation_origine', type: 'uuid', obligatoire: true, commentaire: 'Operation de caisse dorigine.' },
      { nom: 'id_operation_inverse', type: 'uuid', obligatoire: true, commentaire: 'Operation de correction creee.' },
      { nom: 'type_operation', type: 'varchar', taille: 40, obligatoire: true, commentaire: "Type d'operation inverse." },
      { nom: 'montant', type: 'integer', obligatoire: true, commentaire: 'Montant inverse.' },
      { nom: 'devise', type: 'varchar', taille: 8, obligatoire: true, commentaire: 'Devise du montant.' },
      { nom: 'mode_paiement', type: 'varchar', taille: 40, obligatoire: true, commentaire: 'Mode de paiement corrige.' },
      { nom: 'cree_le', type: 'timestamptz', obligatoire: true, commentaire: 'Date de creation de loperation inverse.' },
    ],
    references: [
      { colonneLocale: 'id_annulation', tableReferencee: 'annulations_paiement', colonneReferencee: 'id', actionSuppression: 'cascade', actionMiseAJour: 'cascade', commentaire: "Reference vers l'annulation parente." },
    ],
    index: [],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'dettes_eleves',
    description: 'Vue denormalisee persistante des dettes consolidees par eleve.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id'],
    colonnes: [
      identifiant("Identifiant technique de la dette consolidee."),
      { nom: 'id_eleve', type: 'uuid', obligatoire: true, commentaire: 'Eleve concerne.' },
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire de la dette consolidee.' },
      { nom: 'dettes_par_annee', type: 'jsonb', obligatoire: true, commentaire: 'Structure consolidee des dettes par annee.' },
      { nom: 'total_arrieres', type: 'jsonb', obligatoire: true, commentaire: 'Total des arrieres.' },
      { nom: 'total_annee_active', type: 'jsonb', obligatoire: true, commentaire: 'Total de lannee active.' },
      { nom: 'total_global', type: 'jsonb', obligatoire: true, commentaire: 'Total global consolide.' },
    ],
    references: [],
    index: [
      { nom: 'ux_dettes_eleves_id_eleve', colonnes: ['id_eleve'], unique: true, commentaire: 'Garantit une synthese unique par eleve.' },
    ],
  }),
  creerSchemaTablePostgresPaiements({
    nomTable: 'compteurs_recus_paiement',
    description: 'Compteurs techniques de numerotation des recus.',
    strategieIsolationTenant: 'directe',
    colonneTenant: 'id_ecole',
    clePrimaire: ['id_ecole', 'annee_reference'],
    colonnes: [
      { nom: 'id_ecole', type: 'uuid', obligatoire: true, commentaire: 'Ecole proprietaire du compteur.' },
      { nom: 'annee_reference', type: 'integer', obligatoire: true, commentaire: 'Annee civile de numerotation.' },
      { nom: 'valeur_courante', type: 'integer', obligatoire: true, valeurParDefautSql: '0', commentaire: 'Derniere valeur attribuee.' },
    ],
    references: [],
    index: [],
  }),
];
