import type { AuditPostgresTableSchema } from './audit-postgres-schema.types';

// Ce schema decrit la table append-only principale du module Audit.
export const auditEntriesSchema: AuditPostgresTableSchema = {
  table: 'audit_entries',
  mission: "Table append-only officielle representant la verite historique du module Audit.",
  zone: 'transactionnelle',
  appendOnly: true,
  colonnes: [
    { nom: 'id_audit_entry', definitionSql: 'UUID PRIMARY KEY', critique: true },
    { nom: 'action', definitionSql: 'VARCHAR(150) NOT NULL', critique: true, justification: 'Classification exploitee par analytics et forensic.' },
    { nom: 'type_principal', definitionSql: 'VARCHAR(80) NOT NULL', critique: true },
    { nom: 'gravite', definitionSql: 'VARCHAR(30) NOT NULL', critique: true },
    { nom: 'niveau', definitionSql: 'VARCHAR(30) NOT NULL', critique: true },
    { nom: 'resultat', definitionSql: 'VARCHAR(30) NOT NULL', critique: true },
    { nom: 'request_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'correlation_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'session_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'sync_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'replay_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'acteur_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'type_acteur', definitionSql: 'VARCHAR(50) NOT NULL', critique: true },
    { nom: 'role_actif', definitionSql: 'VARCHAR(80) NULL', critique: true, justification: 'Le contexte historique de permission doit etre preserve.' },
    { nom: 'type_ressource', definitionSql: 'VARCHAR(80) NULL', critique: true },
    { nom: 'id_ressource', definitionSql: 'UUID NULL', critique: true },
    { nom: 'libelle_ressource', definitionSql: 'VARCHAR(255) NULL' },
    { nom: 'organisation_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'ecole_id', definitionSql: 'UUID NULL', critique: true },
    { nom: 'scope', definitionSql: 'VARCHAR(80) NOT NULL', critique: true },
    { nom: 'mode_offline', definitionSql: 'BOOLEAN NOT NULL DEFAULT FALSE', critique: true },
    { nom: 'statut_synchronisation', definitionSql: 'VARCHAR(40) NULL', critique: true },
    { nom: 'retry_count', definitionSql: 'INTEGER NOT NULL DEFAULT 0', critique: true },
    { nom: 'est_replay', definitionSql: 'BOOLEAN NOT NULL DEFAULT FALSE', critique: true },
    { nom: 'est_retry', definitionSql: 'BOOLEAN NOT NULL DEFAULT FALSE', critique: true },
    { nom: 'adresse_ip', definitionSql: 'VARCHAR(120) NULL', critique: true },
    { nom: 'user_agent', definitionSql: 'TEXT NULL', critique: true },
    { nom: 'device_id', definitionSql: 'VARCHAR(255) NULL', critique: true },
    { nom: 'source_audit', definitionSql: 'VARCHAR(80) NOT NULL', critique: true },
    { nom: 'source_runtime', definitionSql: 'VARCHAR(80) NULL' },
    { nom: 'version_application', definitionSql: 'VARCHAR(80) NULL' },
    { nom: 'date_action', definitionSql: 'TIMESTAMPTZ NOT NULL', critique: true },
    { nom: 'date_creation_audit', definitionSql: 'TIMESTAMPTZ NOT NULL', critique: true },
    { nom: 'date_synchronisation', definitionSql: 'TIMESTAMPTZ NULL', critique: true },
    { nom: 'ancien_etat', definitionSql: 'JSONB NULL', critique: true },
    { nom: 'nouvel_etat', definitionSql: 'JSONB NULL', critique: true },
    { nom: 'metadata', definitionSql: 'JSONB NULL', critique: true },
    { nom: 'contexte_permissions', definitionSql: 'JSONB NULL', critique: true },
    { nom: 'contexte_execution', definitionSql: 'JSONB NULL', critique: true },
  ],
  contraintes: [
    { type: 'primary_key', expression: 'PRIMARY KEY (id_audit_entry)' },
    { type: 'not_null', expression: 'action, type_principal, gravite, resultat, source_audit, date_action, date_creation_audit' },
    { type: 'check', expression: 'CHECK (retry_count >= 0)', justification: 'Contrainte explicitement recommandee par le document.' },
    { type: 'append_only_guard', expression: 'Interdire UPDATE audit_entries et DELETE audit_entries', justification: 'Protection append-only attendue au niveau SQL.' },
  ],
  jsonbAutorises: ['ancien_etat', 'nouvel_etat', 'metadata', 'contexte_permissions', 'contexte_execution'],
  jsonbInterdits: ['password', 'motDePasse', 'jwt', 'refresh_token', 'secret', 'fichier_binaire'],
  preparations: [
    { type: 'indexation', details: ['acteur_id', 'organisation_id', 'ecole_id', 'gravite', 'type_principal', 'date_action', 'correlation_id', 'request_id', 'id_ressource', 'statut_synchronisation', 'device_id'] },
    { type: 'partitionnement', details: ['partition temporelle', 'partition tenant', 'partition archive'] },
    { type: 'forensic', details: ['correlation_id', 'request_id', 'device_id critiques pour reconstruction et tracing'] },
    { type: 'offline', details: ['replay', 'retry', 'sync differee', 'conflits', 'chronologies multiples', 'appareils multiples'] },
    { type: 'archivage', details: ['conservation longue', 'cold storage futur', 'migration archive', 'lecture archive'] },
  ],
};
