import type {
  FrontendActorCode,
  FrontendActorProfile,
  FrontendModuleDoctrine,
  FrontendPageDoctrine,
} from './doctrine.types';

const plateformeActors = ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'] as const satisfies readonly FrontendActorCode[];
const monitoringReadActors = ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'] as const satisfies readonly FrontendActorCode[];
const organizationActors = ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'] as const satisfies readonly FrontendActorCode[];
const schoolTechActors = ['ADMIN_SYSTEME_ECOLE'] as const satisfies readonly FrontendActorCode[];
const schoolGovernanceActors = ['ADMINISTRATEUR_ECOLE'] as const satisfies readonly FrontendActorCode[];
const schoolFinanceActors = ['CAISSIER', 'COMPTABLE', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'] as const satisfies readonly FrontendActorCode[];
const pedagogicalSupervisionActors = [
  'ENSEIGNANT',
  'PREFET_ETUDES',
  'DIRECTEUR_ETUDES',
  'DIRECTEUR_PRIMAIRE',
  'DIRECTEUR_MATERNELLE',
] as const satisfies readonly FrontendActorCode[];
const notificationSchoolActors = [
  'ADMIN_SYSTEME_ECOLE',
  'ADMINISTRATEUR_ECOLE',
  'PREFET_ETUDES',
  'DIRECTEUR_ETUDES',
  'DIRECTEUR_PRIMAIRE',
  'DIRECTEUR_MATERNELLE',
  'DIRECTEUR_DISCIPLINE',
] as const satisfies readonly FrontendActorCode[];

export const actorProfiles: readonly FrontendActorProfile[] = [
  {
    code: 'MANAGER_SYSTEME',
    label: 'Manager systeme',
    displayName: 'Nadia Ilunga',
    homeRoute: '/app/plateforme',
    governanceLevels: ['PLATEFORME'],
  },
  {
    code: 'OPERATEUR_SYSTEME',
    label: 'Operateur systeme',
    displayName: 'Joel Banza',
    homeRoute: '/app/plateforme',
    governanceLevels: ['PLATEFORME'],
  },
  {
    code: 'SUPPORT_SYSTEME',
    label: 'Support systeme',
    displayName: 'Sarah Mbuyi',
    homeRoute: '/app/monitoring',
    governanceLevels: ['PLATEFORME'],
  },
  {
    code: 'PROMOTEUR_ORGANISATION',
    label: 'Promoteur organisation',
    displayName: 'Daniel Kikunda',
    homeRoute: '/app/organisation',
    governanceLevels: ['ORGANISATION'],
  },
  {
    code: 'ADMIN_SYSTEME_ORGANISATION',
    label: 'Admin systeme organisation',
    displayName: 'Grace Kabamba',
    homeRoute: '/app/organisation',
    governanceLevels: ['ORGANISATION'],
  },
  {
    code: 'GESTIONNAIRE_ORGANISATION',
    label: 'Gestionnaire organisation',
    displayName: 'Patrick Mutombo',
    homeRoute: '/app/organisation',
    governanceLevels: ['ORGANISATION'],
  },
  {
    code: 'ADMIN_SYSTEME_ECOLE',
    label: 'Admin systeme ecole',
    displayName: 'Patrick Mulumba',
    homeRoute: '/app/academique/annees-scolaires',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'ADMINISTRATEUR_ECOLE',
    label: 'Administrateur ecole',
    displayName: 'Chantal Lukusa',
    homeRoute: '/app/finances/caisse',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'CAISSIER',
    label: 'Caissier',
    displayName: 'Daniel Kikunda',
    homeRoute: '/app/finances/paiements/enregistrer',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'COMPTABLE',
    label: 'Comptable',
    displayName: 'Josephine Ilunga',
    homeRoute: '/app/audit/ecole/administratif-financier',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'SECRETAIRE',
    label: 'Secretaire',
    displayName: 'Rachel Kalonji',
    homeRoute: '/app/finances/exonerations',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'ENSEIGNANT',
    label: 'Enseignant',
    displayName: 'Michel Kabeya',
    homeRoute: '/app/pedagogique/fiches-cotation',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'PREFET_ETUDES',
    label: 'Prefet des etudes',
    displayName: 'Ruth Mukendi',
    homeRoute: '/app/pedagogique/resultats/analyses',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'DIRECTEUR_ETUDES',
    label: 'Directeur des etudes',
    displayName: 'Jean Kanku',
    homeRoute: '/app/pedagogique/resultats/analyses',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'DIRECTEUR_DISCIPLINE',
    label: 'Directeur de discipline',
    displayName: 'Didier Banza',
    homeRoute: '/app/pedagogique/conduite',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'DIRECTEUR_PRIMAIRE',
    label: 'Directeur primaire',
    displayName: 'Mireille Tshiaba',
    homeRoute: '/app/scolarite/cycle-vie',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'DIRECTEUR_MATERNELLE',
    label: 'Directeur maternelle',
    displayName: 'Aline Mbayo',
    homeRoute: '/app/scolarite/cycle-vie',
    governanceLevels: ['ECOLE'],
  },
  {
    code: 'PARENT',
    label: 'Parent',
    displayName: 'Aline Mwepu',
    homeRoute: '/app/finances/historiques',
    governanceLevels: ['ECOLE'],
  },
];

export const moduleDoctrine: readonly FrontendModuleDoctrine[] = [
  {
    code: 'PLATEFORME',
    label: 'Plateforme',
    description: 'Pilotage systeme global, referentiel officiel et operations amont de niveau plateforme.',
    icon: 'Command',
    route: '/app/plateforme',
    ownerLevels: ['PLATEFORME'],
  },
  {
    code: 'ORGANISATION',
    label: 'Organisation',
    description: 'Creation des organisations, lecture des ecoles rattachees et gouvernance organisationnelle.',
    icon: 'Network',
    route: '/app/organisation',
    ownerLevels: ['PLATEFORME', 'ORGANISATION'],
  },
  {
    code: 'ADMINISTRATION_ECOLE',
    label: 'Administration ecole',
    description: 'Creation, activation et institutionnalisation des ecoles avant exploitation locale.',
    icon: 'Building',
    route: '/app/administration-ecole',
    ownerLevels: ['PLATEFORME'],
  },
  {
    code: 'FINANCES',
    label: 'Paiements et facturation',
    description: 'Perception, caisse, recus, situation financiere et analyses de recouvrement.',
    icon: 'WalletCards',
    route: '/app/finances',
    ownerLevels: ['ORGANISATION', 'ECOLE'],
  },
  {
    code: 'PEDAGOGIQUE',
    label: 'Pedagogique',
    description: 'Fiches, resultats, bulletins, proclamations, analyses, classements et conduite.',
    icon: 'GraduationCap',
    route: '/app/pedagogique',
    ownerLevels: ['ECOLE'],
  },
  {
    code: 'SCOLARITE',
    label: 'Scolarite',
    description: 'Inscription, eleves, familles, affectations, cycle de vie et suspensions.',
    icon: 'School',
    route: '/app/scolarite',
    ownerLevels: ['ECOLE'],
  },
  {
    code: 'ACADEMIQUE',
    label: 'Academique',
    description: 'Exploitation academique locale de l ecole : annees, classes pedagogiques, calendriers et programmes niveau.',
    icon: 'BookOpenCheck',
    route: '/app/academique',
    ownerLevels: ['ECOLE'],
  },
  {
    code: 'MONITORING',
    label: 'Monitoring',
    description: 'Etat systeme, incidents, alertes, diagnostics, capacite et traces.',
    icon: 'Activity',
    route: '/app/monitoring',
    ownerLevels: ['PLATEFORME'],
  },
  {
    code: 'AUDIT',
    label: 'Audit',
    description: 'Traces et controles accessibles selon votre perimetre.',
    icon: 'Shield',
    route: '/app/audit',
    ownerLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
  },
  {
    code: 'CONFIGURATION',
    label: 'Configuration',
    description: 'Runtime plateforme, politiques organisationnelles et parametrage local.',
    icon: 'Settings2',
    route: '/app/configuration',
    ownerLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
  },
  {
    code: 'NOTIFICATIONS',
    label: 'Notifications',
    description: 'Diffusion locale, supervision organisationnelle et operations techniques.',
    icon: 'Bell',
    route: '/app/notifications',
    ownerLevels: ['ORGANISATION', 'ECOLE'],
  },
  {
    code: 'SECURITY',
    label: 'Security',
    description: 'Roles, affectations, scopes, verifications et audit security.',
    icon: 'LockKeyhole',
    route: '/app/security',
    ownerLevels: ['PLATEFORME'],
  },
];

export const pageDoctrine: readonly FrontendPageDoctrine[] = [
  {
    code: 'PLAT-HOME',
    routeName: 'platform-home',
    routePath: '/app/plateforme',
    label: 'Centre plateforme',
    moduleCode: 'PLATEFORME',
    sectionCode: 'home',
    sectionLabel: 'Centre plateforme',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.consulter', label: 'Consulter le centre plateforme' }],
  },
  {
    code: 'PLAT-REF-001',
    routeName: 'platform-reference-read',
    routePath: '/app/plateforme/referentiel',
    label: 'Referentiel officiel',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'liste',
    icon: 'LibraryBig',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.read', label: 'Lire le referentiel officiel' }],
  },
  {
    code: 'PLAT-REF-002',
    routeName: 'platform-reference-publish',
    routePath: '/app/plateforme/referentiel/publier',
    label: 'Publication referentiel',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'action',
    icon: 'Send',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.publish', label: 'Publier une version officielle' }],
  },
  {
    code: 'PLAT-REF-003',
    routeName: 'platform-reference-activate',
    routePath: '/app/plateforme/referentiel/activer',
    label: 'Activation referentiel',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'action',
    icon: 'CircleCheckBig',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.activate', label: 'Activer une version officielle' }],
  },
  {
    code: 'PLAT-REF-004',
    routeName: 'platform-reference-import',
    routePath: '/app/plateforme/referentiel/importer',
    label: 'Import referentiel',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'action',
    icon: 'Download',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.import', label: 'Importer un referentiel officiel' }],
  },
  {
    code: 'PLAT-REF-005',
    routeName: 'platform-reference-compare',
    routePath: '/app/plateforme/referentiel/comparer',
    label: 'Comparaison referentiel',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'analyse',
    icon: 'GitCompareArrows',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.compare', label: 'Comparer deux versions officielles' }],
  },
  {
    code: 'PLAT-REF-006',
    routeName: 'platform-reference-migrations',
    routePath: '/app/plateforme/referentiel/migrations',
    label: 'Migrations referentielles',
    moduleCode: 'PLATEFORME',
    sectionCode: 'referentiel',
    sectionLabel: 'Referentiel officiel',
    pageType: 'action',
    icon: 'ArrowRightLeft',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'platform.referentiel.migrate', label: 'Executer une migration referentielle' }],
  },
  {
    code: 'ORG-HOME',
    routeName: 'organization-home',
    routePath: '/app/organisation',
    label: 'Centre organisation',
    moduleCode: 'ORGANISATION',
    sectionCode: 'home',
    sectionLabel: 'Centre organisation',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['PLATEFORME', 'ORGANISATION'],
    visibleActions: [{ code: 'organization.consulter', label: 'Consulter le centre organisation' }],
  },
  {
    code: 'ORG-001',
    routeName: 'organization-registry',
    routePath: '/app/organisation/ecoles',
    label: 'Registre des organisations',
    moduleCode: 'ORGANISATION',
    sectionCode: 'registre',
    sectionLabel: 'Registre organisationnel',
    pageType: 'liste',
    icon: 'Building2',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'organization.read', label: 'Lire le registre des organisations' },
      { code: 'organization.write', label: 'Creer ou muter une organisation' },
    ],
  },
  {
    code: 'ORG-001-DETAIL',
    routeName: 'organization-detail',
    routePath: '/app/organisation/organisations/:idOrganisation',
    label: 'Voir organisation',
    moduleCode: 'ORGANISATION',
    sectionCode: 'registre',
    sectionLabel: 'Registre organisationnel',
    pageType: 'detail',
    icon: 'FileSearch',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'organization.detail.read', label: 'Lire le detail d une organisation' },
      { code: 'organization.detail.activate-context', label: 'Activer l organisation dans le contexte' },
    ],
  },
  {
    code: 'ORG-001-EDIT',
    routeName: 'organization-edit',
    routePath: '/app/organisation/organisations/:idOrganisation/modifier',
    label: 'Modifier organisation',
    moduleCode: 'ORGANISATION',
    sectionCode: 'registre',
    sectionLabel: 'Registre organisationnel',
    pageType: 'action',
    icon: 'PencilLine',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'organization.write', label: 'Modifier le nom d une organisation' }],
  },
  {
    code: 'ORG-001-SCHOOLS',
    routeName: 'organization-attached-schools',
    routePath: '/app/organisation/organisations/:idOrganisation/ecoles',
    label: 'Ecoles rattachees',
    moduleCode: 'ORGANISATION',
    sectionCode: 'registre',
    sectionLabel: 'Registre organisationnel',
    pageType: 'liste',
    icon: 'School',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'organization.schools.read', label: 'Lire les ecoles rattachees a une organisation' },
      { code: 'organization.school.detail.read', label: 'Ouvrir une ecole rattachee' },
    ],
  },
  {
    code: 'ORG-002',
    routeName: 'organization-school-detail',
    routePath: '/app/organisation/ecoles/:idEcole',
    label: 'Detail ecole organisation',
    moduleCode: 'ORGANISATION',
    sectionCode: 'registre',
    sectionLabel: 'Registre organisationnel',
    pageType: 'detail',
    icon: 'School',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'organization.school.detail.read', label: 'Lire le detail d une ecole rattachee' }],
  },
  {
    code: 'ORG-003',
    routeName: 'organization-configuration',
    routePath: '/app/organisation/configuration',
    label: 'Configuration organisationnelle',
    moduleCode: 'ORGANISATION',
    sectionCode: 'configuration',
    sectionLabel: 'Configuration',
    pageType: 'parametrage',
    icon: 'Settings2',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [
      { code: 'organization.configuration.read', label: 'Lire la configuration organisationnelle' },
      { code: 'organization.configuration.manage', label: 'Piloter la configuration organisationnelle' },
    ],
  },
  {
    code: 'ADM-HOME',
    routeName: 'school-administration-home',
    routePath: '/app/administration-ecole',
    label: 'Centre administration ecole',
    moduleCode: 'ADMINISTRATION_ECOLE',
    sectionCode: 'home',
    sectionLabel: 'Centre administration ecole',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'referentiel.read', label: 'Consulter le centre administration ecole (ADM-01)' }],
  },
  {
    code: 'ADM-001',
    routeName: 'school-administration-registry',
    routePath: '/app/administration-ecole/ecoles',
    label: 'Registre des ecoles',
    moduleCode: 'ADMINISTRATION_ECOLE',
    sectionCode: 'registre',
    sectionLabel: 'Registre des ecoles',
    pageType: 'liste',
    icon: 'School',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      {
        code: 'referentiel.read',
        label: 'Lire le registre des ecoles (ADM-01)',
        actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
      },
      {
        code: 'referentiel.write',
        label: 'Creer ou muter une ecole (ADM-01)',
        actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
      },
    ],
  },
  {
    code: 'ADM-002',
    routeName: 'school-administration-detail',
    routePath: '/app/administration-ecole/ecoles/:idEcole',
    label: 'Detail ecole',
    moduleCode: 'ADMINISTRATION_ECOLE',
    sectionCode: 'registre',
    sectionLabel: 'Registre des ecoles',
    pageType: 'detail',
    icon: 'FileSearch',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      {
        code: 'referentiel.read',
        label: 'Lire le detail d une ecole (ADM-01)',
        actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
      },
      {
        code: 'referentiel.write',
        label: 'Muter une ecole (ADM-01)',
        actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
      },
      {
        code: 'configuration.modules.school.write',
        label: 'Configurer les modules actifs de l ecole',
        actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
      },
    ],
  },
  {
    code: 'ACA-HOME',
    routeName: 'academique-home',
    routePath: '/app/academique',
    label: 'Centre academique',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'home',
    sectionLabel: 'Centre academique',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.consulter', label: 'Consulter le centre academique' }],
  },
  {
    code: 'ACA-REF-001',
    routeName: 'academique-referentiels',
    routePath: '/app/academique/referentiels',
    label: 'Referentiels academiques',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'referentiels',
    sectionLabel: 'Referentiels',
    pageType: 'liste',
    icon: 'LibraryBig',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.read', label: 'Lire le referentiel officiel' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-PUB-001',
    routeName: 'academique-publication',
    routePath: '/app/academique/publication',
    label: 'Publication referentiel',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'publication',
    sectionLabel: 'Publication',
    pageType: 'action',
    icon: 'Send',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.publish', label: 'Publier un referentiel' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-ACT-001',
    routeName: 'academique-activation',
    routePath: '/app/academique/activation',
    label: 'Activation referentiel',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'activation',
    sectionLabel: 'Activation',
    pageType: 'action',
    icon: 'CircleCheckBig',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.activate', label: 'Activer une version' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-IMP-001',
    routeName: 'academique-imports',
    routePath: '/app/academique/imports',
    label: 'Import referentiel',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'imports',
    sectionLabel: 'Imports',
    pageType: 'action',
    icon: 'Download',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.import', label: 'Importer un referentiel' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-CMP-001',
    routeName: 'academique-comparaisons',
    routePath: '/app/academique/comparaisons',
    label: 'Comparaison referentiel',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'comparaisons',
    sectionLabel: 'Comparaisons',
    pageType: 'analyse',
    icon: 'GitCompareArrows',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.compare', label: 'Comparer deux versions' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-MIG-001',
    routeName: 'academique-migrations',
    routePath: '/app/academique/migrations',
    label: 'Migration referentielle',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'migrations',
    sectionLabel: 'Migrations',
    pageType: 'action',
    icon: 'ArrowRightLeft',
    actorCodes: ['MANAGER_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'academique.referentiels.migrate', label: 'Executer une migration' }],
    hiddenInNavigation: true,
  },
  {
    code: 'ACA-LOC-001',
    routeName: 'academique-annees-scolaires',
    routePath: '/app/academique/annees-scolaires',
    label: 'Annees scolaires',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'annees',
    sectionLabel: 'Annees scolaires',
    pageType: 'parametrage',
    icon: 'CalendarClock',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.local.school-years.manage', label: 'Piloter les annees scolaires' }],
  },
  {
    code: 'ACA-LOC-002',
    routeName: 'academique-classes-pedagogiques',
    routePath: '/app/academique/classes-pedagogiques',
    label: 'Classes pedagogiques',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'classes',
    sectionLabel: 'Classes pedagogiques',
    pageType: 'parametrage',
    icon: 'Blocks',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.local.classes.manage', label: 'Gerer les classes pedagogiques' }],
  },
  {
    code: 'ACA-LOC-003',
    routeName: 'academique-responsabilites-classes',
    routePath: '/app/academique/responsabilites-classes',
    label: 'Responsabilites de classes',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'responsabilites',
    sectionLabel: 'Responsables de classe',
    pageType: 'parametrage',
    icon: 'UserRoundCog',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.local.responsables.manage', label: 'Gerer les responsables de classe' }],
  },
  {
    code: 'ACA-LOC-004',
    routeName: 'academique-calendriers',
    routePath: '/app/academique/calendriers',
    label: 'Calendrier academique',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'calendriers',
    sectionLabel: 'Calendrier',
    pageType: 'parametrage',
    icon: 'CalendarRange',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.local.calendar.manage', label: 'Cadrer le calendrier academique' }],
  },
  {
    code: 'ACA-LOC-005',
    routeName: 'academique-programmes-locaux',
    routePath: '/app/academique/programmes-locaux',
    label: 'Programmes niveau',
    moduleCode: 'ACADEMIQUE',
    sectionCode: 'programmes',
    sectionLabel: 'Programmes locaux',
    pageType: 'parametrage',
    icon: 'BookMarked',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'academique.local.programmes.manage', label: 'Piloter les programmes locaux' }],
  },

  {
    code: 'PED-HOME',
    routeName: 'pedagogique-home',
    routePath: '/app/pedagogique',
    label: 'Centre pedagogique',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'home',
    sectionLabel: 'Centre pedagogique',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: [
      'ENSEIGNANT',
      'PREFET_ETUDES',
      'DIRECTEUR_ETUDES',
      'DIRECTEUR_DISCIPLINE',
      'DIRECTEUR_PRIMAIRE',
      'DIRECTEUR_MATERNELLE',
      'PARENT',
    ],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'pedagogique.consulter', label: 'Consulter le centre pedagogique' }],
  },
  {
    code: 'PED-001',
    routeName: 'pedagogique-fiche-cotation-electronique',
    routePath: '/app/pedagogique/fiches-cotation',
    label: 'Fiche de cotation electronique',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'fiches',
    sectionLabel: 'Fiches de bulletin',
    pageType: 'action',
    icon: 'NotebookPen',
    actorCodes: ['ENSEIGNANT'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'pedagogique.fiches.read', label: 'Lire la fiche' },
      { code: 'pedagogique.fiches.write', label: 'Encoder les cotes' },
    ],
  },
  {
    code: 'PED-008',
    routeName: 'pedagogique-centre-analyse',
    routePath: '/app/pedagogique/resultats/analyses',
    label: 'Centre d analyse pedagogique',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'analyses',
    sectionLabel: 'Analyses de resultats',
    pageType: 'analyse',
    icon: 'ChartColumnBig',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'pedagogique.resultats.read', label: 'Consulter les resultats consolides' },
      { code: 'pedagogique.analyses.read', label: 'Lire les analyses et diagnostics' },
    ],
  },
  {
    code: 'PED-DET-001',
    routeName: 'pedagogique-detail-resultat-eleve',
    routePath: '/app/pedagogique/resultats/detail',
    label: 'Detail resultat eleve',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'resultats',
    sectionLabel: 'Resultats',
    pageType: 'detail',
    icon: 'FileSearch',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE', 'PARENT'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'pedagogique.resultats.detail.read', label: 'Lire le detail d un resultat' }],
  },
  {
    code: 'PED-STAT-001',
    routeName: 'pedagogique-statistiques-classe',
    routePath: '/app/pedagogique/statistiques/classe',
    label: 'Statistiques pedagogiques de classe',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'statistiques',
    sectionLabel: 'Statistiques',
    pageType: 'analyse',
    icon: 'LineChart',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'pedagogique.statistiques.read', label: 'Consulter les statistiques de classe' }],
  },
  {
    code: 'PED-006',
    routeName: 'pedagogique-classement-classe',
    routePath: '/app/pedagogique/classements/classe',
    label: 'Classement de classe',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'classements',
    sectionLabel: 'Classements',
    pageType: 'analyse',
    icon: 'Trophy',
    actorCodes: ['ENSEIGNANT'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'pedagogique.classements.read', label: 'Lire le classement' },
      { code: 'pedagogique.classements.recompute', label: 'Recalculer le classement' },
    ],
  },
  {
    code: 'PED-007',
    routeName: 'pedagogique-encodage-conduite',
    routePath: '/app/pedagogique/conduite',
    label: 'Encodage de la conduite',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'conduite',
    sectionLabel: 'Conduite',
    pageType: 'action',
    icon: 'BadgeCheck',
    actorCodes: ['ENSEIGNANT', 'DIRECTEUR_DISCIPLINE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'pedagogique.conduite.read', label: 'Lire la conduite' },
      { code: 'pedagogique.conduite.write', label: 'Encoder ou modifier la conduite' },
    ],
  },
  {
    code: 'PED-002',
    routeName: 'pedagogique-generation-bulletin',
    routePath: '/app/pedagogique/bulletins/generation',
    label: 'Generation du bulletin',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'bulletins',
    sectionLabel: 'Bulletins',
    pageType: 'action',
    icon: 'FileOutput',
    actorCodes: ['ENSEIGNANT'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'pedagogique.bulletins.generate', label: 'Generer un bulletin' }],
  },
  {
    code: 'PED-003',
    routeName: 'pedagogique-generation-proclamation',
    routePath: '/app/pedagogique/proclamations/generation',
    label: 'Generation de la proclamation',
    moduleCode: 'PEDAGOGIQUE',
    sectionCode: 'proclamations',
    sectionLabel: 'Proclamations',
    pageType: 'action',
    icon: 'Medal',
    actorCodes: ['ENSEIGNANT'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'pedagogique.proclamations.generate', label: 'Generer une proclamation' }],
  },

  {
    code: 'SCO-HOME',
    routeName: 'scolarite-home',
    routePath: '/app/scolarite',
    label: 'Centre scolarite',
    moduleCode: 'SCOLARITE',
    sectionCode: 'home',
    sectionLabel: 'Centre scolarite',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE', 'DIRECTEUR_DISCIPLINE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.consulter', label: 'Consulter le centre scolarite' }],
  },
  {
    code: 'SCO-001',
    routeName: 'scolarite-inscriptions',
    routePath: '/app/scolarite/inscriptions',
    label: 'Inscription scolaire complete',
    moduleCode: 'SCOLARITE',
    sectionCode: 'inscription',
    sectionLabel: 'Inscription',
    pageType: 'action',
    icon: 'UserPlus',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.inscription.write', label: 'Inscrire un eleve' }],
  },
  {
    code: 'SCO-002',
    routeName: 'scolarite-eleves',
    routePath: '/app/scolarite/eleves',
    label: 'Gestion des eleves',
    moduleCode: 'SCOLARITE',
    sectionCode: 'eleves',
    sectionLabel: 'Eleves',
    pageType: 'liste',
    icon: 'Users',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.eleves.manage', label: 'Consulter et gerer les eleves' }],
  },
  {
    code: 'SCO-003',
    routeName: 'scolarite-familles',
    routePath: '/app/scolarite/familles',
    label: 'Gestion des familles',
    moduleCode: 'SCOLARITE',
    sectionCode: 'familles',
    sectionLabel: 'Familles',
    pageType: 'liste',
    icon: 'House',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.familles.manage', label: 'Consulter et gerer les familles' }],
  },
  {
    code: 'SCO-005',
    routeName: 'scolarite-affectations',
    routePath: '/app/scolarite/affectations',
    label: 'Affectations de classe',
    moduleCode: 'SCOLARITE',
    sectionCode: 'affectations',
    sectionLabel: 'Affectations',
    pageType: 'action',
    icon: 'Waypoints',
    actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.affectations.manage', label: 'Gerer les affectations' }],
  },
  {
    code: 'SCO-004',
    routeName: 'scolarite-cycle-vie',
    routePath: '/app/scolarite/cycle-vie',
    label: 'Cycle de vie eleve',
    moduleCode: 'SCOLARITE',
    sectionCode: 'cycle-vie',
    sectionLabel: 'Cycle de vie',
    pageType: 'action',
    icon: 'GitBranchPlus',
    actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE', 'DIRECTEUR_DISCIPLINE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'scolarite.cycle.read', label: 'Lire le cycle de vie' },
      {
        code: 'scolarite.cycle.abandon',
        label: 'Declarer un abandon',
        actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
      },
      {
        code: 'scolarite.cycle.transfert',
        label: 'Declarer un transfert',
        actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
      },
      {
        code: 'scolarite.cycle.reintegration',
        label: 'Declarer une reintegration',
        actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
      },
      {
        code: 'scolarite.cycle.reactivation',
        label: 'Declarer une reactivation',
        actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
      },
      {
        code: 'scolarite.cycle.deces',
        label: 'Declarer un deces',
        actorCodes: ['CAISSIER', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
      },
      {
        code: 'scolarite.cycle.suspension',
        label: 'Appliquer une suspension',
        actorCodes: ['PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE', 'DIRECTEUR_DISCIPLINE'],
      },
    ],
  },
  {
    code: 'SCO-006',
    routeName: 'scolarite-suspensions',
    routePath: '/app/scolarite/suspensions',
    label: 'Suspension eleve',
    moduleCode: 'SCOLARITE',
    sectionCode: 'suspensions',
    sectionLabel: 'Suspensions',
    pageType: 'action',
    icon: 'CircleSlash2',
    actorCodes: ['PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE', 'DIRECTEUR_DISCIPLINE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'scolarite.suspensions.write', label: 'Suspendre un eleve' }],
  },

  {
    code: 'PF-HOME',
    routeName: 'finances-home',
    routePath: '/app/finances',
    label: 'Centre finances',
    moduleCode: 'FINANCES',
    sectionCode: 'home',
    sectionLabel: 'Centre financier',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION', 'PARENT', 'SECRETAIRE'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.consulter', label: 'Consulter le centre financier' }],
  },
  {
    code: 'PF-01',
    routeName: 'finances-perception-paiement',
    routePath: '/app/finances/paiements/enregistrer',
    label: 'Perception de paiement',
    moduleCode: 'FINANCES',
    sectionCode: 'perception',
    sectionLabel: 'Perception',
    pageType: 'action',
    icon: 'HandCoins',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.payments.record', label: 'Enregistrer un paiement' }],
  },
  {
    code: 'PF-02',
    routeName: 'finances-ouverture-caisse',
    routePath: '/app/finances/caisse/ouverture',
    label: 'Ouverture de caisse',
    moduleCode: 'FINANCES',
    sectionCode: 'caisse',
    sectionLabel: 'Caisse',
    pageType: 'action',
    icon: 'Vault',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.cash.open', label: 'Ouvrir la caisse' }],
  },
  {
    code: 'PF-03',
    routeName: 'finances-cloture-caisse',
    routePath: '/app/finances/caisse/cloture',
    label: 'Cloture de caisse',
    moduleCode: 'FINANCES',
    sectionCode: 'caisse',
    sectionLabel: 'Caisse',
    pageType: 'action',
    icon: 'Vault',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.cash.close', label: 'Cloturer la caisse' }],
  },
  {
    code: 'PF-05',
    routeName: 'finances-caisse-du-jour',
    routePath: '/app/finances/caisse',
    label: 'Caisse du jour',
    moduleCode: 'FINANCES',
    sectionCode: 'caisse',
    sectionLabel: 'Caisse',
    pageType: 'centre',
    icon: 'Vault',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.cash.read', label: 'Consulter la caisse du jour' }],
  },
  {
    code: 'PF-10',
    routeName: 'finances-historique-paiements-eleve',
    routePath: '/app/finances/historiques',
    label: 'Historique des paiements',
    moduleCode: 'FINANCES',
    sectionCode: 'historiques',
    sectionLabel: 'Historique paiements',
    pageType: 'detail',
    icon: 'ReceiptText',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION', 'PARENT'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.history.read', label: 'Consulter l historique des paiements' }],
  },
  {
    code: 'PF-11',
    routeName: 'finances-situation-financiere-eleve',
    routePath: '/app/finances/dettes',
    label: 'Situation financiere eleve',
    moduleCode: 'FINANCES',
    sectionCode: 'dettes',
    sectionLabel: 'Dettes et situation financiere',
    pageType: 'detail',
    icon: 'CircleDollarSign',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION', 'PARENT'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.debt.read', label: 'Consulter la situation financiere' }],
  },
  {
    code: 'PF-09',
    routeName: 'finances-recu-paiement',
    routePath: '/app/finances/recus/:idRecu',
    label: 'Recu de paiement',
    moduleCode: 'FINANCES',
    sectionCode: 'recus',
    sectionLabel: 'Recus',
    pageType: 'detail',
    icon: 'ReceiptText',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [
      { code: 'finances.receipts.read', label: 'Consulter un recu' },
      { code: 'finances.receipts.reprint', label: 'Reimprimer un recu' },
    ],
  },
  {
    code: 'PF-08',
    routeName: 'finances-restitution-excedent',
    routePath: '/app/finances/paiements/restitution',
    label: 'Restitution d excedent',
    moduleCode: 'FINANCES',
    sectionCode: 'perception',
    sectionLabel: 'Perception',
    pageType: 'action',
    icon: 'Undo2',
    actorCodes: ['CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.payments.refund', label: 'Restituer un excedent' }],
  },
  {
    code: 'VF-01',
    routeName: 'finances-registre-financier-classe',
    routePath: '/app/finances/registre-classe',
    label: 'Registre financier de classe',
    moduleCode: 'FINANCES',
    sectionCode: 'analyses',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'TableProperties',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [
      { code: 'finances.registre.read', label: 'Consulter le registre financier de classe' },
      { code: 'finances.registre.export', label: 'Exporter le registre' },
    ],
  },
  {
    code: 'VF-02',
    routeName: 'finances-synthese-financiere-classe',
    routePath: '/app/finances/synthese-classe',
    label: 'Synthese financiere de classe',
    moduleCode: 'FINANCES',
    sectionCode: 'analyses',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'ChartColumnBig',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.synthese-classe.read', label: 'Lire la synthese de classe' }],
  },
  {
    code: 'VF-03',
    routeName: 'finances-synthese-financiere-section',
    routePath: '/app/finances/synthese-section',
    label: 'Synthese financiere de section',
    moduleCode: 'FINANCES',
    sectionCode: 'analyses',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'ChartColumnBig',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.synthese-section.read', label: 'Lire la synthese de section' }],
  },
  {
    code: 'VF-04',
    routeName: 'finances-synthese-financiere-ecole',
    routePath: '/app/finances/synthese-ecole',
    label: 'Synthese financiere d ecole',
    moduleCode: 'FINANCES',
    sectionCode: 'analyses',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'ChartColumnBig',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.synthese-ecole.read', label: 'Lire la synthese d ecole' }],
  },
  {
    code: 'VF-05',
    routeName: 'finances-synthese-financiere-organisation',
    routePath: '/app/finances/synthese-organisation',
    label: 'Synthese financiere d organisation',
    moduleCode: 'FINANCES',
    sectionCode: 'analyses',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'Building2',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [{ code: 'finances.synthese-organisation.read', label: 'Lire la synthese d organisation' }],
  },
  {
    code: 'PF-14',
    routeName: 'finances-analyse-paiements-type-frais',
    routePath: '/app/finances/rapports',
    label: 'Analyse paiements par type de frais',
    moduleCode: 'FINANCES',
    sectionCode: 'rapports',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'FileBarChart',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.analytics.read', label: 'Analyser les paiements par type de frais' }],
  },
  {
    code: 'PF-18',
    routeName: 'finances-exonerations',
    routePath: '/app/finances/exonerations',
    label: 'Exonerations',
    moduleCode: 'FINANCES',
    sectionCode: 'exonerations',
    sectionLabel: 'Exonerations',
    pageType: 'parametrage',
    icon: 'ShieldCheck',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'CAISSIER', 'SECRETAIRE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.exonerations.manage', label: 'Gerer les exonerations' }],
  },
  {
    code: 'PF-09-LIST',
    routeName: 'finances-recus-liste',
    routePath: '/app/finances/recus',
    label: 'Recus emis',
    moduleCode: 'FINANCES',
    sectionCode: 'recus',
    sectionLabel: 'Recus',
    pageType: 'liste',
    icon: 'ReceiptText',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.receipts.list', label: 'Consulter les recus emis' }],
  },
  {
    code: 'PF-15',
    routeName: 'finances-rapport-financier-journalier',
    routePath: '/app/finances/rapports/journalier',
    label: 'Rapport financier journalier',
    moduleCode: 'FINANCES',
    sectionCode: 'rapports',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'FileBarChart',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.report.daily.read', label: 'Lire le rapport journalier' }],
  },
  {
    code: 'PF-16',
    routeName: 'finances-paiements-par-caissier',
    routePath: '/app/finances/rapports/paiements-par-caissier',
    label: 'Paiements par caissier',
    moduleCode: 'FINANCES',
    sectionCode: 'rapports',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'Users',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.report.cashiers.read', label: 'Lire les paiements par caissier' }],
  },
  {
    code: 'PF-17',
    routeName: 'finances-fonds-anticipes',
    routePath: '/app/finances/rapports/fonds-anticipes',
    label: 'Fonds anticipes',
    moduleCode: 'FINANCES',
    sectionCode: 'rapports',
    sectionLabel: 'Rapports et analyses',
    pageType: 'analyse',
    icon: 'WalletCards',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.report.advances.read', label: 'Lire les fonds anticipes' }],
  },
  {
    code: 'PF-15-ARR',
    routeName: 'finances-arrieres-eleve',
    routePath: '/app/finances/arrieres',
    label: 'Arrieres eleve',
    moduleCode: 'FINANCES',
    sectionCode: 'dettes',
    sectionLabel: 'Dettes et situation financiere',
    pageType: 'detail',
    icon: 'AlarmClockCheck',
    actorCodes: ['CAISSIER', 'ADMINISTRATEUR_ECOLE', 'PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'finances.arrieres.read', label: 'Consulter les arrieres' }],
  },
  {
    code: 'PF-19',
    routeName: 'finances-parametres-paiement',
    routePath: '/app/finances/parametres',
    label: 'Parametres de paiement',
    moduleCode: 'FINANCES',
    sectionCode: 'parametres',
    sectionLabel: 'Parametres paiement',
    pageType: 'parametrage',
    icon: 'SlidersHorizontal',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.settings.manage', label: 'Gerer les parametres de paiement' }],
  },
  {
    code: 'PF-13',
    routeName: 'finances-tarification',
    routePath: '/app/finances/tarification',
    label: 'Tarification',
    moduleCode: 'FINANCES',
    sectionCode: 'tarification',
    sectionLabel: 'Tarification',
    pageType: 'parametrage',
    icon: 'BadgePercent',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'CAISSIER'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'finances.pricing.manage', label: 'Gerer les grilles de tarification' }],
  },

  {
    code: 'MON-HOME',
    routeName: 'monitoring-home',
    routePath: '/app/monitoring',
    label: 'Centre monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'home',
    sectionLabel: 'Centre monitoring',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'monitoring.consulter', label: 'Consulter le centre monitoring' }],
  },
  {
    code: 'MON-001',
    routeName: 'monitoring-state',
    routePath: '/app/monitoring/etat-systeme',
    label: 'Etat systeme',
    moduleCode: 'MONITORING',
    sectionCode: 'etat',
    sectionLabel: 'Etat systeme',
    pageType: 'analyse',
    icon: 'Server',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'monitoring.state.read', label: 'Lire l etat systeme' }],
  },
  {
    code: 'MON-002',
    routeName: 'monitoring-dashboard',
    routePath: '/app/monitoring/dashboard',
    label: 'Dashboard monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'dashboard',
    sectionLabel: 'Dashboard monitoring',
    pageType: 'analyse',
    icon: 'PanelsTopLeft',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'monitoring.dashboard.read', label: 'Lire le dashboard monitoring' }],
  },
  {
    code: 'MON-003',
    routeName: 'monitoring-observability',
    routePath: '/app/monitoring/observabilite',
    label: 'Observabilite',
    moduleCode: 'MONITORING',
    sectionCode: 'observabilite',
    sectionLabel: 'Observabilite',
    pageType: 'analyse',
    icon: 'Radar',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'monitoring.observability.read', label: 'Lire les signaux d observabilite' }],
  },
  {
    code: 'MON-004',
    routeName: 'monitoring-health',
    routePath: '/app/monitoring/sante',
    label: 'Sante systeme',
    moduleCode: 'MONITORING',
    sectionCode: 'sante',
    sectionLabel: 'Sante systeme',
    pageType: 'analyse',
    icon: 'HeartPulse',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'monitoring.health.read', label: 'Lire la sante systeme' }],
  },
  {
    code: 'MON-005',
    routeName: 'monitoring-incidents',
    routePath: '/app/monitoring/incidents',
    label: 'Incidents monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'incidents',
    sectionLabel: 'Incidents',
    pageType: 'centre',
    icon: 'Siren',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'monitoring.incidents.read', label: 'Lire les incidents' },
      { code: 'monitoring.incidents.open', label: 'Ouvrir un incident' },
      { code: 'monitoring.incidents.escalate', label: 'Escalader un incident' },
    ],
  },
  {
    code: 'MON-006',
    routeName: 'monitoring-alerts',
    routePath: '/app/monitoring/alertes',
    label: 'Alertes monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'alertes',
    sectionLabel: 'Alertes',
    pageType: 'centre',
    icon: 'BellRing',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'monitoring.alerts.read', label: 'Lire les alertes' },
      { code: 'monitoring.alerts.create', label: 'Creer une alerte' },
      { code: 'monitoring.alerts.resolve', label: 'Resoudre une alerte' },
    ],
  },
  {
    code: 'MON-007',
    routeName: 'monitoring-diagnostics',
    routePath: '/app/monitoring/diagnostics',
    label: 'Diagnostics monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'diagnostics',
    sectionLabel: 'Diagnostics',
    pageType: 'analyse',
    icon: 'Stethoscope',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'monitoring.diagnostics.read', label: 'Lire les diagnostics' },
      { code: 'monitoring.diagnostics.generate', label: 'Generer un diagnostic' },
    ],
  },
  {
    code: 'MON-008',
    routeName: 'monitoring-capacity',
    routePath: '/app/monitoring/capacite',
    label: 'Capacite monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'capacite',
    sectionLabel: 'Capacite',
    pageType: 'analyse',
    icon: 'ChartNoAxesCombined',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'monitoring.capacity.read', label: 'Lire la capacite' },
      { code: 'monitoring.capacity.compute', label: 'Calculer la capacite' },
      { code: 'monitoring.saturation.compute', label: 'Calculer la saturation' },
    ],
  },
  {
    code: 'MON-009',
    routeName: 'monitoring-traces',
    routePath: '/app/monitoring/traces',
    label: 'Traces monitoring',
    moduleCode: 'MONITORING',
    sectionCode: 'traces',
    sectionLabel: 'Traces',
    pageType: 'analyse',
    icon: 'ScanSearch',
    actorCodes: monitoringReadActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'monitoring.traces.read', label: 'Lire les traces' },
      { code: 'monitoring.traces.capture', label: 'Capturer une trace' },
    ],
  },

  {
    code: 'AUD-HOME',
    routeName: 'audit-home',
    routePath: '/app/audit',
    label: 'Centre audit',
    moduleCode: 'AUDIT',
    sectionCode: 'home',
    sectionLabel: 'Centre audit',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: [
      'MANAGER_SYSTEME',
      'OPERATEUR_SYSTEME',
      'SUPPORT_SYSTEME',
      'PROMOTEUR_ORGANISATION',
      'GESTIONNAIRE_ORGANISATION',
      'ADMINISTRATEUR_ECOLE',
      'ADMIN_SYSTEME_ECOLE',
      'CAISSIER',
      'COMPTABLE',
      'PREFET_ETUDES',
      'DIRECTEUR_ETUDES',
      'DIRECTEUR_DISCIPLINE',
      'DIRECTEUR_PRIMAIRE',
      'DIRECTEUR_MATERNELLE',
    ],
    governanceLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'audit.consulter', label: 'Consulter le centre audit' }],
  },
  {
    code: 'AUD-PLAT-001',
    routeName: 'audit-platform',
    routePath: '/app/audit/plateforme',
    label: 'Audit plateforme',
    moduleCode: 'AUDIT',
    sectionCode: 'plateforme',
    sectionLabel: 'Audit plateforme',
    pageType: 'analyse',
    icon: 'ServerCog',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'audit.platform.read', label: 'Consulter l audit plateforme' },
      { code: 'audit.platform.timeline.read', label: 'Consulter une chronologie' },
      { code: 'audit.platform.history.read', label: 'Consulter un historique' },
      { code: 'audit.platform.export', label: 'Demander un export' },
      { code: 'audit.platform.export.read', label: 'Suivre un export' },
      { code: 'audit.platform.export.download', label: 'Telecharger un export' },
      { code: 'audit.platform.export.delete', label: 'Supprimer un fichier exporte' },
      { code: 'audit.platform.forensic.export', label: 'Exporter une investigation' },
      { code: 'audit.platform.replay', label: 'Reconstruire une projection' },
      { code: 'audit.platform.retention.read', label: 'Consulter les archives' },
      { code: 'audit.platform.retention.archive', label: 'Archiver des evenements' },
      { code: 'audit.platform.retention.preview', label: 'Previsualiser la retention' },
      { code: 'audit.platform.integrity.read', label: 'Verifier l integrite' },
    ],
  },
  {
    code: 'AUD-PLAT-002',
    routeName: 'audit-platform-event-detail',
    routePath: '/app/audit/plateforme/evenements/:auditId',
    label: 'Detail evenement audit',
    moduleCode: 'AUDIT',
    sectionCode: 'plateforme',
    sectionLabel: 'Audit plateforme',
    pageType: 'detail',
    icon: 'FileSearch',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME', 'SUPPORT_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'audit.platform.read', label: 'Consulter l audit plateforme' }],
    hiddenInNavigation: true,
  },
  {
    code: 'AUD-ORG-001',
    routeName: 'audit-organization',
    routePath: '/app/audit/organisation',
    label: 'Audit organisationnel',
    moduleCode: 'AUDIT',
    sectionCode: 'organisation',
    sectionLabel: 'Audit organisationnel',
    pageType: 'analyse',
    icon: 'Building2',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [{ code: 'audit.organization.read', label: 'Consulter l audit organisationnel' }],
  },
  {
    code: 'AUD-ECO-001',
    routeName: 'audit-school-financial',
    routePath: '/app/audit/ecole/administratif-financier',
    label: 'Audit administratif et financier',
    moduleCode: 'AUDIT',
    sectionCode: 'ecole-adm-fin',
    sectionLabel: 'Audit administratif et financier',
    pageType: 'analyse',
    icon: 'ClipboardCheck',
    actorCodes: ['ADMINISTRATEUR_ECOLE', 'CAISSIER', 'COMPTABLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.school.financial.read', label: 'Consulter l audit administratif et financier' }],
  },
  {
    code: 'AUD-ECO-002',
    routeName: 'audit-school-technical',
    routePath: '/app/audit/ecole/technique',
    label: 'Audit technique ecole',
    moduleCode: 'AUDIT',
    sectionCode: 'ecole-tech',
    sectionLabel: 'Audit technique',
    pageType: 'analyse',
    icon: 'LaptopMinimalCheck',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.school.technical.read', label: 'Consulter l audit technique' }],
  },
  {
    code: 'AUD-PED-001',
    routeName: 'audit-pedagogical-cotes',
    routePath: '/app/audit/pedagogique/cotes',
    label: 'Audit pedagogique cotes',
    moduleCode: 'AUDIT',
    sectionCode: 'pedagogique',
    sectionLabel: 'Audit pedagogique',
    pageType: 'analyse',
    icon: 'BookCheck',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_PRIMAIRE', 'DIRECTEUR_MATERNELLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.pedagogique.cotes.read', label: 'Consulter l audit pedagogique des cotes' }],
  },
  {
    code: 'AUD-PED-002',
    routeName: 'audit-pedagogical-conduite',
    routePath: '/app/audit/pedagogique/conduite',
    label: 'Audit pedagogique conduite',
    moduleCode: 'AUDIT',
    sectionCode: 'pedagogique',
    sectionLabel: 'Audit pedagogique',
    pageType: 'analyse',
    icon: 'BadgeCheck',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES', 'DIRECTEUR_DISCIPLINE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.pedagogique.conduite.read', label: 'Consulter l audit pedagogique de conduite' }],
  },
  {
    code: 'AUD-PED-003',
    routeName: 'audit-pedagogical-bulletins',
    routePath: '/app/audit/pedagogique/bulletins',
    label: 'Audit pedagogique bulletins',
    moduleCode: 'AUDIT',
    sectionCode: 'pedagogique',
    sectionLabel: 'Audit pedagogique',
    pageType: 'analyse',
    icon: 'FileOutput',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.pedagogique.bulletins.read', label: 'Consulter l audit des bulletins' }],
  },
  {
    code: 'AUD-PED-004',
    routeName: 'audit-pedagogical-classements',
    routePath: '/app/audit/pedagogique/classements',
    label: 'Audit pedagogique classements',
    moduleCode: 'AUDIT',
    sectionCode: 'pedagogique',
    sectionLabel: 'Audit pedagogique',
    pageType: 'analyse',
    icon: 'Trophy',
    actorCodes: ['ENSEIGNANT', 'PREFET_ETUDES', 'DIRECTEUR_ETUDES'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'audit.pedagogique.classements.read', label: 'Consulter l audit des classements' }],
  },

  {
    code: 'CFG-HOME',
    routeName: 'configuration-home',
    routePath: '/app/configuration',
    label: 'Centre configuration',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'home',
    sectionLabel: 'Centre configuration',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: [
      'MANAGER_SYSTEME',
      'OPERATEUR_SYSTEME',
      'SUPPORT_SYSTEME',
      'PROMOTEUR_ORGANISATION',
      'ADMIN_SYSTEME_ORGANISATION',
      'GESTIONNAIRE_ORGANISATION',
      'ADMIN_SYSTEME_ECOLE',
      'ADMINISTRATEUR_ECOLE',
    ],
    governanceLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'configuration.consulter', label: 'Consulter le centre configuration' }],
  },
  {
    code: 'CFG-PLAT-001',
    routeName: 'configuration-platform-runtime',
    routePath: '/app/configuration/plateforme/runtime',
    label: 'Runtime plateforme',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'runtime',
    sectionLabel: 'Runtime plateforme',
    pageType: 'parametrage',
    icon: 'Cpu',
    actorCodes: ['MANAGER_SYSTEME', 'OPERATEUR_SYSTEME'],
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'configuration.platform.runtime.manage', label: 'Gerer le runtime plateforme' }],
  },
  {
    code: 'CFG-ORG-001',
    routeName: 'configuration-organization',
    routePath: '/app/configuration/organisation',
    label: 'Configuration organisationnelle',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'organisation',
    sectionLabel: 'Organisation',
    pageType: 'parametrage',
    icon: 'Building2',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [
      { code: 'configuration.organization.read', label: 'Lire la configuration organisationnelle' },
      { code: 'configuration.organization.manage', label: 'Piloter la configuration organisationnelle' },
    ],
  },
  {
    code: 'CFG-ORG-002',
    routeName: 'configuration-organization-modules',
    routePath: '/app/configuration/organisation/modules',
    label: 'Modules organisation',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'organisation-modules',
    sectionLabel: 'Organisation',
    pageType: 'parametrage',
    icon: 'ToggleLeft',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [{ code: 'configuration.organization.modules.manage', label: 'Piloter les modules organisation' }],
  },
  {
    code: 'CFG-ECO-001',
    routeName: 'configuration-school-modules',
    routePath: '/app/configuration/ecole/modules',
    label: 'Modules ecole',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'ecole-modules',
    sectionLabel: 'Ecole',
    pageType: 'parametrage',
    icon: 'ToggleLeft',
    actorCodes: ['ADMIN_SYSTEME_ECOLE', 'ADMINISTRATEUR_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'configuration.school.modules.manage', label: 'Gerer les modules ecole' }],
  },
  {
    code: 'CFG-ECO-002',
    routeName: 'configuration-school-branding',
    routePath: '/app/configuration/ecole/branding',
    label: 'Branding ecole',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'branding',
    sectionLabel: 'Branding',
    pageType: 'parametrage',
    icon: 'Palette',
    actorCodes: ['ADMIN_SYSTEME_ECOLE', 'ADMINISTRATEUR_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'configuration.school.branding.manage', label: 'Gerer le branding ecole' }],
  },
  {
    code: 'CFG-ECO-003',
    routeName: 'configuration-school-notifications',
    routePath: '/app/configuration/ecole/notifications',
    label: 'Notifications ecole',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'notifications',
    sectionLabel: 'Notifications',
    pageType: 'parametrage',
    icon: 'Bell',
    actorCodes: ['ADMIN_SYSTEME_ECOLE', 'ADMINISTRATEUR_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'configuration.school.notifications.manage', label: 'Gerer les notifications ecole' }],
  },
  {
    code: 'CFG-USER-001',
    routeName: 'configuration-user-preferences',
    routePath: '/app/configuration/utilisateur/preferences',
    label: 'Preferences utilisateur',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'preferences',
    sectionLabel: 'Preferences utilisateur',
    pageType: 'parametrage',
    icon: 'UserCog',
    actorCodes: actorProfiles.map((profile) => profile.code),
    governanceLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'configuration.user.preferences.manage', label: 'Gerer les preferences utilisateur' }],
  },
  {
    code: 'CFG-USER-002',
    routeName: 'me-preferences',
    routePath: '/app/moi/preferences',
    label: 'Mes preferences',
    moduleCode: 'CONFIGURATION',
    sectionCode: 'preferences',
    sectionLabel: 'Preferences utilisateur',
    pageType: 'parametrage',
    icon: 'UserCog',
    actorCodes: actorProfiles.map((profile) => profile.code),
    governanceLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'configuration.user.preferences.self', label: 'Mettre a jour mes preferences' }],
  },

  {
    code: 'NOTIF-HOME',
    routeName: 'notifications-home',
    routePath: '/app/notifications',
    label: 'Centre notifications',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'home',
    sectionLabel: 'Centre notifications',
    pageType: 'home',
    icon: 'LayoutGrid',
    actorCodes: [
      'MANAGER_SYSTEME',
      'OPERATEUR_SYSTEME',
      'ADMIN_SYSTEME_ECOLE',
      'ADMINISTRATEUR_ECOLE',
      'PREFET_ETUDES',
      'DIRECTEUR_ETUDES',
      'DIRECTEUR_PRIMAIRE',
      'DIRECTEUR_MATERNELLE',
      'DIRECTEUR_DISCIPLINE',
      'PROMOTEUR_ORGANISATION',
      'ADMIN_SYSTEME_ORGANISATION',
      'GESTIONNAIRE_ORGANISATION',
    ],
    governanceLevels: ['PLATEFORME', 'ORGANISATION', 'ECOLE'],
    visibleActions: [{ code: 'notifications.consulter', label: 'Consulter le centre notifications' }],
  },
  {
    code: 'NOTIF-ECO-001',
    routeName: 'notifications-school-compose',
    routePath: '/app/notifications/ecole/envoyer',
    label: 'Envoyer notification locale',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'ecole',
    sectionLabel: 'Diffusion ecole',
    pageType: 'action',
    icon: 'Send',
    actorCodes: notificationSchoolActors,
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'notifications.school.send', label: 'Envoyer une notification locale' }],
  },
  {
    code: 'NOTIF-ECO-002',
    routeName: 'notifications-school-operations',
    routePath: '/app/notifications/ecole/operations',
    label: 'Operations techniques notifications',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'technique',
    sectionLabel: 'Operations techniques',
    pageType: 'action',
    icon: 'Workflow',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'notifications.school.dead-letter.read', label: 'Lire la dead-letter' },
      { code: 'notifications.school.retry', label: 'Relancer une operation' },
      { code: 'notifications.school.replay', label: 'Rejouer un flux' },
    ],
  },
  {
    code: 'NOTIF-ECO-003',
    routeName: 'notifications-school-dead-letter',
    routePath: '/app/notifications/ecole/dead-letter',
    label: 'Dead-letter notifications',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'technique',
    sectionLabel: 'Operations techniques',
    pageType: 'analyse',
    icon: 'Mailbox',
    actorCodes: ['ADMIN_SYSTEME_ECOLE'],
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'notifications.school.dead-letter.read', label: 'Lire la dead-letter' }],
  },
  {
    code: 'NOTIF-ECO-004',
    routeName: 'notifications-school-center',
    routePath: '/app/notifications/ecole',
    label: 'Centre local notifications',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'ecole',
    sectionLabel: 'Diffusion ecole',
    pageType: 'centre',
    icon: 'School',
    actorCodes: notificationSchoolActors,
    governanceLevels: ['ECOLE'],
    visibleActions: [
      { code: 'notifications.school.list.read', label: 'Lister les notifications locales' },
      { code: 'notifications.school.detail.read', label: 'Consulter le detail d une notification' },
      { code: 'notifications.school.timeline.read', label: 'Consulter la timeline locale' },
      { code: 'notifications.school.monitoring.read', label: 'Consulter le monitoring local' },
      { code: 'notifications.school.acknowledge', label: 'Accuser reception d une notification' },
      { code: 'notifications.school.escalate', label: 'Escalader une notification' },
    ],
  },
  {
    code: 'NOTIF-ECO-005',
    routeName: 'notifications-school-detail',
    routePath: '/app/notifications/ecole/:idNotification',
    label: 'Detail notification locale',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'ecole',
    sectionLabel: 'Diffusion ecole',
    pageType: 'detail',
    icon: 'FileSearch',
    actorCodes: notificationSchoolActors,
    governanceLevels: ['ECOLE'],
    visibleActions: [{ code: 'notifications.school.detail.read', label: 'Consulter le detail d une notification' }],
  },
  {
    code: 'NOTIF-ORG-001',
    routeName: 'notifications-organization-realtime',
    routePath: '/app/notifications/organisation/realtime',
    label: 'Temps reel notifications organisation',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'organisation',
    sectionLabel: 'Supervision organisationnelle',
    pageType: 'analyse',
    icon: 'RadioTower',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [
      { code: 'notifications.organization.realtime.read', label: 'Lire les capacites temps reel' },
      { code: 'notifications.organization.realtime.publish-test', label: 'Publier un test temps reel' },
    ],
  },
  {
    code: 'NOTIF-ORG-002',
    routeName: 'notifications-organization-escalations',
    routePath: '/app/notifications/organisation/escalades',
    label: 'Escalades notifications organisation',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'organisation',
    sectionLabel: 'Supervision organisationnelle',
    pageType: 'analyse',
    icon: 'ArrowUpRight',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [{ code: 'notifications.organization.escalations.read', label: 'Consulter les escalades' }],
  },
  {
    code: 'NOTIF-ORG-003',
    routeName: 'notifications-organization',
    routePath: '/app/notifications/organisation',
    label: 'Supervision notifications organisation',
    moduleCode: 'NOTIFICATIONS',
    sectionCode: 'organisation',
    sectionLabel: 'Supervision organisationnelle',
    pageType: 'centre',
    icon: 'Building2',
    actorCodes: ['PROMOTEUR_ORGANISATION', 'ADMIN_SYSTEME_ORGANISATION', 'GESTIONNAIRE_ORGANISATION'],
    governanceLevels: ['ORGANISATION'],
    visibleActions: [
      { code: 'notifications.organization.read', label: 'Consulter la supervision organisationnelle' },
      { code: 'notifications.organization.archives.read', label: 'Consulter les archives organisationnelles' },
      { code: 'notifications.organization.tenant.read', label: 'Consulter la vue tenant organisationnelle' },
      { code: 'notifications.organization.escalations.read', label: 'Consulter les escalades' },
    ],
  },

  {
    code: 'SEC-HOME',
    routeName: 'security-home',
    routePath: '/app/security',
    label: 'Centre Sécurité',
    moduleCode: 'SECURITY',
    sectionCode: 'home',
    sectionLabel: 'Gouvernance des accès',
    pageType: 'centre',
    icon: 'ShieldCheck',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [
      { code: 'security.center.read', label: 'Consulter le Centre Sécurité' },
      { code: 'security.accounts.write', label: 'Créer des comptes Plateforme' },
      { code: 'security.accounts.lifecycle', label: 'Gérer le cycle de vie des comptes' },
      { code: 'security.sessions.revoke', label: 'Révoquer des connexions' },
      { code: 'security.audit.read', label: 'Consulter l’historique de sécurité' },
    ],
  },
  {
    code: 'SEC-001',
    routeName: 'security-roles',
    routePath: '/app/security/roles',
    label: 'Rôles et permissions',
    moduleCode: 'SECURITY',
    sectionCode: 'roles',
    sectionLabel: 'Roles',
    pageType: 'detail',
    icon: 'IdCard',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.roles.manage', label: 'Gerer les roles et permissions' }],
  },
  {
    code: 'SEC-001-DETAIL',
    routeName: 'security-role-detail',
    routePath: '/app/security/roles/:codeRole',
    label: 'Detail role security',
    moduleCode: 'SECURITY',
    sectionCode: 'roles',
    sectionLabel: 'Roles',
    pageType: 'detail',
    icon: 'IdCard',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.roles.detail.read', label: 'Lire le detail d un role' }],
  },
  {
    code: 'SEC-002',
    routeName: 'security-assignments',
    routePath: '/app/security/affectations',
    label: 'Affectations et périmètres',
    moduleCode: 'SECURITY',
    sectionCode: 'affectations',
    sectionLabel: 'Affectations',
    pageType: 'detail',
    icon: 'UserCheck',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.assignments.manage', label: 'Gerer les affectations security' }],
  },
  {
    code: 'SEC-002-DETAIL',
    routeName: 'security-user-assignments',
    routePath: '/app/security/affectations/utilisateurs/:idUtilisateur',
    label: 'Affectations utilisateur security',
    moduleCode: 'SECURITY',
    sectionCode: 'affectations',
    sectionLabel: 'Affectations',
    pageType: 'detail',
    icon: 'UserCheck',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.assignments.user.read', label: 'Lire les affectations d un utilisateur' }],
  },
  {
    code: 'SEC-003',
    routeName: 'security-titulariats',
    routePath: '/app/security/titulariats',
    label: 'Titulariats security',
    moduleCode: 'SECURITY',
    sectionCode: 'affectations',
    sectionLabel: 'Affectations',
    pageType: 'detail',
    icon: 'BookUser',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.titulariats.manage', label: 'Relire les titulariats effectifs' }],
  },
  {
    code: 'SEC-004',
    routeName: 'security-checks',
    routePath: '/app/security/verifications',
    label: 'Verifications security',
    moduleCode: 'SECURITY',
    sectionCode: 'verifications',
    sectionLabel: 'Verifications',
    pageType: 'detail',
    icon: 'BadgeCheck',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.checks.run', label: 'Executer les verifications security' }],
  },
  {
    code: 'SEC-005',
    routeName: 'security-audit',
    routePath: '/app/security/audit',
    label: 'Historique de sécurité',
    moduleCode: 'SECURITY',
    sectionCode: 'audit',
    sectionLabel: 'Audit security',
    pageType: 'detail',
    icon: 'ShieldAlert',
    actorCodes: plateformeActors,
    governanceLevels: ['PLATEFORME'],
    visibleActions: [{ code: 'security.audit.read', label: 'Consulter l audit security' }],
  },
];
