// Ce fichier porte les motifs officiels expliquant un non-classement.
export enum MotifNonClasse {
  COTE_MANQUANTE = 'COTE_MANQUANTE',
  COURS_CALCULABLE_NON_ENCODE = 'COURS_CALCULABLE_NON_ENCODE',
  COLONNE_OBLIGATOIRE_MANQUANTE = 'COLONNE_OBLIGATOIRE_MANQUANTE',
  ABSENCE_STRUCTURE_EVALUATION = 'ABSENCE_STRUCTURE_EVALUATION',
}
