// Ce fichier porte la nomenclature officielle des anomalies academiques detectables.
export enum TypeAnomalieAcademique {
  COTE_MANQUANTE = 'COTE_MANQUANTE',
  MAXIMUM_INCOHERENT = 'MAXIMUM_INCOHERENT',
  COLONNE_INTERDITE_ENCODEE = 'COLONNE_INTERDITE_ENCODEE',
  TOTAL_ENCODE_MANUELLEMENT = 'TOTAL_ENCODE_MANUELLEMENT',
  EXAMEN_ENCODE_COURS_SANS_EXAMEN = 'EXAMEN_ENCODE_COURS_SANS_EXAMEN',
  REFERENTIEL_INCOMPATIBLE = 'REFERENTIEL_INCOMPATIBLE',
  CLASSEMENT_INCOHERENT = 'CLASSEMENT_INCOHERENT',
  POURCENTAGE_INCOHERENT = 'POURCENTAGE_INCOHERENT',
  RANG_INCOHERENT = 'RANG_INCOHERENT',
  BULLETIN_INCOMPLET = 'BULLETIN_INCOMPLET',
  PROCLAMATION_INCOHERENTE = 'PROCLAMATION_INCOHERENTE',
}
