import type { AuditPostgresIndexDefinition } from './audit-postgres-index.types';

// Ces indexes couvrent la table append-only principale et ses lectures critiques.
export const auditEntriesIndexes: readonly AuditPostgresIndexDefinition[] = [
  {
    nom: 'idx_audit_entries_date_action',
    table: 'audit_entries',
    famille: 'transactionnel',
    methode: 'BTREE',
    colonnes: ['date_action'],
    tri: ['DESC'],
    critique: true,
    partitionFriendly: true,
    justification: "Presque toutes les lectures Audit utilisent ORDER BY date_action DESC.",
  },
  {
    nom: 'idx_audit_entries_action',
    table: 'audit_entries',
    famille: 'transactionnel',
    methode: 'BTREE',
    colonnes: ['action'],
    critique: true,
    justification: "Recherche rapide par type d'action auditée.",
  },
  {
    nom: 'idx_audit_entries_type_principal',
    table: 'audit_entries',
    famille: 'transactionnel',
    methode: 'BTREE',
    colonnes: ['type_principal'],
    critique: true,
    justification: 'Le type principal alimente les recherches et les analytics.',
  },
  {
    nom: 'idx_audit_entries_gravite',
    table: 'audit_entries',
    famille: 'transactionnel',
    methode: 'BTREE',
    colonnes: ['gravite'],
    critique: true,
    justification: 'Très utile pour incidents, alertes sécurité, supervision et forensic.',
  },
  {
    nom: 'idx_audit_entries_tenant',
    table: 'audit_entries',
    famille: 'multi_tenant',
    methode: 'BTREE',
    colonnes: ['organisation_id', 'ecole_id', 'date_action'],
    tri: ['ASC', 'ASC', 'DESC'],
    critique: true,
    partitionFriendly: true,
    justification: 'Presque toutes les lectures filtrent par tenant puis trient chronologiquement.',
  },
  {
    nom: 'idx_audit_entries_tenant_date',
    table: 'audit_entries',
    famille: 'multi_tenant',
    methode: 'BTREE',
    colonnes: ['organisation_id', 'ecole_id', 'date_action'],
    tri: ['ASC', 'ASC', 'DESC'],
    critique: true,
    partitionFriendly: true,
    justification: "Index composite explicitement demandé pour les queries métier tenant + date.",
    notes: ['Alias documentaire du besoin composite principal.'],
  },
  {
    nom: 'idx_audit_entries_acteur_timeline',
    table: 'audit_entries',
    famille: 'timeline',
    methode: 'BTREE',
    colonnes: ['acteur_id', 'date_action'],
    tri: ['ASC', 'DESC'],
    critique: true,
    justification: 'Timeline utilisateur rapide.',
  },
  {
    nom: 'idx_audit_entries_ressource_timeline',
    table: 'audit_entries',
    famille: 'timeline',
    methode: 'BTREE',
    colonnes: ['type_ressource', 'id_ressource', 'date_action'],
    tri: ['ASC', 'ASC', 'DESC'],
    critique: true,
    justification: "Historique complet d'une ressource avec tri chronologique.",
  },
  {
    nom: 'idx_audit_entries_correlation',
    table: 'audit_entries',
    famille: 'forensic',
    methode: 'BTREE',
    colonnes: ['correlation_id'],
    critique: true,
    justification: 'Index central pour reconstruction workflow et chaînes corrélées.',
  },
  {
    nom: 'idx_audit_entries_request',
    table: 'audit_entries',
    famille: 'forensic',
    methode: 'BTREE',
    colonnes: ['request_id'],
    critique: true,
    justification: 'Une requête peut produire plusieurs événements audit liés.',
  },
  {
    nom: 'idx_audit_entries_session',
    table: 'audit_entries',
    famille: 'forensic',
    methode: 'BTREE',
    colonnes: ['session_id'],
    critique: true,
    justification: 'Investigation session et forensic sécurité.',
  },
  {
    nom: 'idx_audit_entries_device',
    table: 'audit_entries',
    famille: 'forensic',
    methode: 'BTREE',
    colonnes: ['device_id'],
    critique: true,
    justification: 'Très critique offline-first pour plusieurs appareils et plusieurs chronologies.',
  },
  {
    nom: 'idx_audit_entries_sync_status',
    table: 'audit_entries',
    famille: 'offline_sync',
    methode: 'BTREE',
    colonnes: ['statut_synchronisation'],
    critique: true,
    justification: 'Permet replay, retry, audits non synchronisés et suivi sync.',
  },
  {
    nom: 'idx_audit_entries_replay_retry',
    table: 'audit_entries',
    famille: 'offline_sync',
    methode: 'BTREE',
    colonnes: ['est_replay', 'est_retry'],
    critique: true,
    justification: 'Forensic sync et identification rapide des cycles replay/retry.',
  },
  {
    nom: 'idx_audit_entries_analytics',
    table: 'audit_entries',
    famille: 'analytics',
    methode: 'BTREE',
    colonnes: ['type_principal', 'date_action'],
    tri: ['ASC', 'DESC'],
    critique: true,
    partitionFriendly: true,
    justification: 'Volumétrie, tendances et statistiques par type principal.',
  },
  {
    nom: 'idx_audit_metadata',
    table: 'audit_entries',
    famille: 'jsonb',
    methode: 'GIN',
    colonnes: ['metadata'],
    critique: false,
    justification: 'JSONB critique indexé stratégiquement, sans indexer tout le chaos documentaire.',
    notes: ['À garder sous discipline car GIN consomme plus de ressources.'],
  },
  {
    nom: 'idx_audit_entries_partition_ready_date',
    table: 'audit_entries',
    famille: 'partitionnement',
    methode: 'BRIN',
    colonnes: ['date_action'],
    critique: false,
    partitionFriendly: true,
    justification: 'Préparation au partition pruning temporel long terme sur grande volumétrie.',
  },
];
