export const AUDIT_PROJECTION_FAMILIES = {
  TIMELINE: 'TIMELINE',
  SECURITY: 'SECURITY',
  ANALYTICS: 'ANALYTICS',
  EXPORTS: 'EXPORTS',
  OFFLINE_SYNC: 'OFFLINE_SYNC',
  SUPERVISION: 'SUPERVISION',
  FORENSIC: 'FORENSIC',
  USER_ACTIVITY: 'USER_ACTIVITY',
  TENANT_ACTIVITY: 'TENANT_ACTIVITY',
  VOLUMETRIE: 'VOLUMETRIE',
} as const;

export type AuditProjectionFamily = typeof AUDIT_PROJECTION_FAMILIES[keyof typeof AUDIT_PROJECTION_FAMILIES];

